{
  "hash": "da6bf307c613d627261860338166d4c3",
  "result": {
    "markdown": "---\ntitle: \"The Joy of Analysis\"\ndate: \"2023-02-27\"\ncategories: [\"#TidyTuesday\", R, \"Data Visuals\"]\ntoc: true\ndraft: false\n---\n\n::: {.cell}\n\n:::\n\n\nAs an artist and TV personality, Bob Ross has captivated audiences for decades with his signature afro, and of course, his beautiful paintings. In this blog post, we will take a closer look at the colors that Bob Ross used during his time on \"The Joy of Painting\". \n\n![](color_trends_by_season.png)\n\n# Introduction\n\n::: {.panel-tabset}\n\n### Introduction \n\n[Bob Ross](https://en.wikipedia.org/wiki/Bob_Ross) was known for his soothing voice, calm demeanor, and his ability to create beautiful landscapes with simple brushstrokes. One of the defining features of his painting was the vibrant and bold colors he used to bring his landscapes to life. Whether you're a fan of [The Joy of Painting](https://en.wikipedia.org/wiki/The_Joy_of_Painting) or simply interested in data analytics, this post will offer you valuable insights. \n\nLet's **consider a viewer** who is **new to painting**, and wants to explore its joy by watching a season of \"The Joy of Painting\", and following along. This viewer is **budget conscious** and might be **disappointed to spend money on paint supplies that are hardly used**. This analysis considers this use case by investigating the frequency of colors used across seasons.   \n\n### Libraries\n\nThis analysis will use packages the [tidyverse](https://www.tidyverse.org/) to wrangle the data, and plotly to make interactive graphs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(plotly)\n```\n:::\n\n\n### Data\n\nThis analysis will only use the Bob Ross data set that is included in [TidyTuesday](https://github.com/rfordatascience/tidytuesday) for February 21, 2023. \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nbob_ross <- read_csv(\n  \"https://raw.githubusercontent.com/jwilber/Bob_Ross_Paintings/master/data/bob_ross_paintings.csv\",\n) \nhead(bob_ross)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 28\n   ...1 painting…¹ img_src paint…² season episode num_c…³ youtu…⁴ colors color…⁵\n  <dbl>      <dbl> <chr>   <chr>    <dbl>   <dbl>   <dbl> <chr>   <chr>  <chr>  \n1     1        282 https:… A Walk…      1       1       8 https:… \"['Al… ['#4E1…\n2     2        283 https:… Mt. Mc…      1       2       8 https:… \"['Al… ['#4E1…\n3     3        284 https:… Ebony …      1       3       9 https:… \"['Al… ['#4E1…\n4     4        285 https:… Winter…      1       4       3 https:… \"['Pr… ['#021…\n5     5        286 https:… Quiet …      1       5       8 https:… \"['Al… ['#4E1…\n6     6        287 https:… Winter…      1       6       4 https:… \"['Bl… ['#000…\n# … with 18 more variables: Black_Gesso <dbl>, Bright_Red <dbl>,\n#   Burnt_Umber <dbl>, Cadmium_Yellow <dbl>, Dark_Sienna <dbl>,\n#   Indian_Red <dbl>, Indian_Yellow <dbl>, Liquid_Black <dbl>,\n#   Liquid_Clear <dbl>, Midnight_Black <dbl>, Phthalo_Blue <dbl>,\n#   Phthalo_Green <dbl>, Prussian_Blue <dbl>, Sap_Green <dbl>,\n#   Titanium_White <dbl>, Van_Dyke_Brown <dbl>, Yellow_Ochre <dbl>,\n#   Alizarin_Crimson <dbl>, and abbreviated variable names ¹​painting_index, …\n```\n:::\n:::\n\n\n\n### Data Cleaning \n\n## episode_per_season\n\n**episode_per_season** : groups the original bob_ross data by season and then counts how many episode is in each season. \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nepisodes_per_season <- bob_ross %>%\n  dplyr::group_by(season) %>%\n  dplyr::summarise(total_episodes = dplyr::n()) \n```\n:::\n\n\n## br_colors\n\n**br_colors** : short for Bob Ross colors, this data groups the original bob_ross data by season, and then counts the total amount of color used that season.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nbr_colors <- bob_ross %>%\n  dplyr::group_by(season) %>%\n  dplyr::summarise(\n    total_num_colors = base::sum(num_colors)) \n```\n:::\n\n\n## br_subset\n\n**br_subset** : short for Bob Ross subset, this data groups the original bob_ross data by season and then counts how many times each color was used in each season.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nbr_subset <- bob_ross %>%\n  dplyr::group_by(season) %>%\n  dplyr::summarise(\n    black_gesso = base::sum(Black_Gesso),\n    bright_red = base::sum(Bright_Red),\n    burnt_umber = base::sum(Burnt_Umber),\n    carmium_yellow = base::sum(Cadmium_Yellow),\n    dark_sienna = base::sum(Dark_Sienna),\n    indian_red = base::sum(Indian_Red),\n    indian_yellow = base::sum(Indian_Yellow),\n    liquid_black = base::sum(Liquid_Black),\n    liquid_clear = base::sum(Liquid_Clear),\n    midnight_black = base::sum(Midnight_Black),\n    phthalo_blue = base::sum(Phthalo_Blue),\n    phthalo_green = base::sum(Phthalo_Green),\n    prussian_blue = base::sum(Prussian_Blue),\n    sap_green = base::sum(Sap_Green),\n    titanium_white = base::sum(Titanium_White),\n    van_dyke_brown = base::sum(Van_Dyke_Brown),\n    yellow_orchre = base::sum(Yellow_Ochre),\n    alizarian_crimson = base::sum(Alizarin_Crimson)\n    ) %>%\n  tidyr::pivot_longer(\n    !season, \n    names_to = \"color\", \n    values_to = \"count\")\n```\n:::\n\n\n### Queries\n\n## Summary Stats\n\n**mean_colors** : Give the average number of colors used a season.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nmean_colors <- base::mean(br_colors$total_num_colors)\nmean_colors\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 137.871\n```\n:::\n:::\n\n\n**min_colors** : Gives the minimum amount of colors used in a season.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nmin_colors <- base::min(br_colors$total_num_colors)\nmin_colors\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 92\n```\n:::\n:::\n\n\n**max_colors** : Gives the max amount of colors used in a season.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nmax_colors <- base::max(br_colors$total_num_colors)\nmax_colors\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 156\n```\n:::\n:::\n\n\n## Color Specific Details\n\n**burnt_umber_details** : Gives the episode number, season, img_src, paiting title, and youtube_scr for all episodes that used burnt umber. \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nburnt_umber_details <- bob_ross %>%\n  dplyr::filter(Burnt_Umber == 1) %>%\n  dplyr::summarise(\n    episode = episode,\n    season = season,\n    img_src = img_src,\n    painting_title = painting_title,\n    youtube_src = youtube_src)\n```\n:::\n\n\n**dark_sienna_details** : Gives the episode number, season, img_src, paiting title, and youtube_scr for all episodes that used dark sienna. \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\ndark_sienna_details <- bob_ross %>%\n  dplyr::filter(Dark_Sienna == 1) %>%\n  dplyr::summarise(\n    episode = episode,\n    season = season,\n    img_src = img_src,\n    painting_title = painting_title,\n    youtube_src = youtube_src)\n```\n:::\n\n\n### Visuals\n\n## colors_graph\n\n**colors_graph** : Is a graph that shows the amount of specific colors used each season. \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nbr_colors <- c(\n  \"#4E1500\", \"#000000\", \"#DB0000\", \n  \"#8A3324\", \"#FFEC00\", \"#5F2E1F\", \n  \"#CD5C5C\", \"#FFB800\", \"#000000\", \n  \"#FFFFFF\", \"#000000\", \"#0C0040\", \n  \"#102E3C\", \"#021E44\", \"#0A3410\", \n  \"#FFFFFF\", \"#221B15\", \"#C79B00\")\ncolors_graph <- ggplot2::ggplot(\n  br_subset, \n  aes(\n    x = season,\n    y = count,\n    fill = color)\n  ) +\n  ggplot2::geom_col(\n    stat = \"identity\",\n    position = \"stack\"\n    ) +\n  ggplot2::ggtitle(\"Colors Used Each Season\") +\n  ggplot2::xlab(\"Season\") +\n  ggplot2::ylab(\"Colors Used\") + \n  ggplot2::scale_fill_manual(values = br_colors) +\n  ggplot2::theme(\n    plot.title = element_text(family = \"Times\"),\n    axis.title.x = element_text(family = \"Times\"),\n    axis.title.y = element_text(family = \"Times\")\n  )\n```\n:::\n\n\n## color_trends\n\n**color_trends** : Is a graph that shows color trends by season. \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\ncolor_labs <- c(black_gesso = \"Black Gesso\", \n                bright_red = \"Bright Red\", \n                burnt_umber = \"Burnt Umber\",\n                carmium_yellow = \"Carmium Yellow\", \n                dark_sienna = \"Dark Sienna\", \n                indian_red = \"Indian Red\",\n                indian_yellow = \"Indian Yellow\", \n                liquid_black = \"Liquid Black\", \n                liquid_clear = \"Liquid Clear\",\n                midnight_black = \"Midnight Black\", \n                phthalo_blue = \"Phthalo Blue\", \n                phthalo_green = \"Phthalo Green\",\n                prussian_blue = \"Prussian Blue\", \n                sap_green = \"Sap Green\", \n                titanium_white = \"Titanium White\",\n                van_dyke_brown = \"Van Dyke Brown\", \n                yellow_orchre = \"Yellow Orchre\", \n                alizarian_crimson = \"Alizarian Crimson\")\n\n# html_colors <- rep(html_colors, 31)\n# br_subset$html_colors <- html_colors\ncolor_trends <- ggplot2::ggplot(\n  br_subset, \n  ggplot2::aes(\n    x = season, \n    y = count)\n  ) +\n  ggplot2::geom_point() +\n  ggplot2::facet_wrap(\n    vars(color), \n    labeller = labeller(color = color_labs)) +\n  ggplot2::ggtitle(\"Color Trends By Season\") +\n  ggplot2::xlab(\"Season\") +\n  ggplot2::ylab(\"Count\") + \n  ggplot2::labs(\n    caption = \"Graph by Randi Bolt\\nData from #TidyTuesday\"\n    ) +\n  ggplot2::theme(\n    plot.title = element_text(family = \"Times\"),\n    axis.title.x = element_text(family = \"Times\"),\n    axis.title.y = element_text(family = \"Times\"),\n    strip.background = element_rect(\n     color=\"#2c1320\", \n     fill= \"#6c464e\", \n     size=1.5, \n     linetype=\"solid\"),\n    strip.text.x = element_text(\n      family = \"Times\",\n      color = \"#feebe2\") \n  ) \n```\n:::\n\n\n\n:::\n\n# Exploritroy Data Analysis \n\n::: {.panel-tabset}\n\n### About \n\n## About \"The Joy of Painting\": \n\n* 31 total seasons.\n\n* 13 episodes per season. \n\n* 403 total episodes. \n\nWhen we consider our use case above, and that a canvas costs about `$`3. Then a budget conscious user can assume their **budget for paint canvas** will be about **`$`40 per season**, and about **`$`1,210 for all 403 episodes**.\n\nBelow is a table that shows the total number of episodes per season. \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n               [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]\nseason            1    2    3    4    5    6    7    8    9    10    11    12\ntotal_episodes   13   13   13   13   13   13   13   13   13    13    13    13\n               [,13] [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22]\nseason            13    14    15    16    17    18    19    20    21    22\ntotal_episodes    13    13    13    13    13    13    13    13    13    13\n               [,23] [,24] [,25] [,26] [,27] [,28] [,29] [,30] [,31]\nseason            23    24    25    26    27    28    29    30    31\ntotal_episodes    13    13    13    13    13    13    13    13    13\n```\n:::\n:::\n\n\n### Colors\n\n## Colors Used\n\n* On **average 138** colors were used each season.\n\n* The **least** amount of colors used in a single season was **92** in season 1. \n\n* The **most** amount of colors used in a single season was **156** in season 14. \n\nWhen considering our use case, a budget conscious viewer may consider starting their journey at season 1 where the least amount of colors are used. \n\nBelow is a table that shows the total number of colors used per season, and a graph that shows the total number of colors used each season stacked by color that was used. \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n     [,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]     \n[1,] \"#4E1500\" \"#000000\" \"#DB0000\" \"#8A3324\" \"#FFEC00\" \"#5F2E1F\" \"#CD5C5C\"\n     [,8]      [,9]      [,10]     [,11]     [,12]     [,13]     [,14]    \n[1,] \"#FFB800\" \"#000000\" \"#FFFFFF\" \"#000000\" \"#0C0040\" \"#102E3C\" \"#021E44\"\n     [,15]     [,16]     [,17]     [,18]    \n[1,] \"#0A3410\" \"#FFFFFF\" \"#221B15\" \"#C79B00\"\n```\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-f2b55f969cf0731258bb\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f2b55f969cf0731258bb\">{\"x\":{\"data\":[{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[81,133,115,118,99,123,112,125,127,136,117,134,127,143,134,122,139,134,132,133,134,138,129,125,132,125,118,120,124,136,129],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[11,12,13,12,12,13,10,13,13,12,11,10,10,13,13,12,13,13,13,13,12,13,12,13,13,11,13,12,13,13,13],\"text\":[\"season:  1<br />count: 11<br />color: alizarian_crimson\",\"season:  2<br />count: 12<br />color: alizarian_crimson\",\"season:  3<br />count: 13<br />color: alizarian_crimson\",\"season:  4<br />count: 12<br />color: alizarian_crimson\",\"season:  5<br />count: 12<br />color: alizarian_crimson\",\"season:  6<br />count: 13<br />color: alizarian_crimson\",\"season:  7<br />count: 10<br />color: alizarian_crimson\",\"season:  8<br />count: 13<br />color: alizarian_crimson\",\"season:  9<br />count: 13<br />color: alizarian_crimson\",\"season: 10<br />count: 12<br />color: alizarian_crimson\",\"season: 11<br />count: 11<br />color: alizarian_crimson\",\"season: 12<br />count: 10<br />color: alizarian_crimson\",\"season: 13<br />count: 10<br />color: alizarian_crimson\",\"season: 14<br />count: 13<br />color: alizarian_crimson\",\"season: 15<br />count: 13<br />color: alizarian_crimson\",\"season: 16<br />count: 12<br />color: alizarian_crimson\",\"season: 17<br />count: 13<br />color: alizarian_crimson\",\"season: 18<br />count: 13<br />color: alizarian_crimson\",\"season: 19<br />count: 13<br />color: alizarian_crimson\",\"season: 20<br />count: 13<br />color: alizarian_crimson\",\"season: 21<br />count: 12<br />color: alizarian_crimson\",\"season: 22<br />count: 13<br />color: alizarian_crimson\",\"season: 23<br />count: 12<br />color: alizarian_crimson\",\"season: 24<br />count: 13<br />color: alizarian_crimson\",\"season: 25<br />count: 13<br />color: alizarian_crimson\",\"season: 26<br />count: 11<br />color: alizarian_crimson\",\"season: 27<br />count: 13<br />color: alizarian_crimson\",\"season: 28<br />count: 12<br />color: alizarian_crimson\",\"season: 29<br />count: 13<br />color: alizarian_crimson\",\"season: 30<br />count: 13<br />color: alizarian_crimson\",\"season: 31<br />count: 13<br />color: alizarian_crimson\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(78,21,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"alizarian_crimson\",\"legendgroup\":\"alizarian_crimson\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[79,130,113,116,97,120,112,123,124,134,115,132,124,140,130,118,135,129,128,131,128,135,125,119,126,120,115,117,121,131,126],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[2,3,2,2,2,3,0,2,3,2,2,2,3,3,4,4,4,5,4,2,6,3,4,6,6,5,3,3,3,5,3],\"text\":[\"season:  1<br />count:  2<br />color: black_gesso\",\"season:  2<br />count:  3<br />color: black_gesso\",\"season:  3<br />count:  2<br />color: black_gesso\",\"season:  4<br />count:  2<br />color: black_gesso\",\"season:  5<br />count:  2<br />color: black_gesso\",\"season:  6<br />count:  3<br />color: black_gesso\",\"season:  7<br />count:  0<br />color: black_gesso\",\"season:  8<br />count:  2<br />color: black_gesso\",\"season:  9<br />count:  3<br />color: black_gesso\",\"season: 10<br />count:  2<br />color: black_gesso\",\"season: 11<br />count:  2<br />color: black_gesso\",\"season: 12<br />count:  2<br />color: black_gesso\",\"season: 13<br />count:  3<br />color: black_gesso\",\"season: 14<br />count:  3<br />color: black_gesso\",\"season: 15<br />count:  4<br />color: black_gesso\",\"season: 16<br />count:  4<br />color: black_gesso\",\"season: 17<br />count:  4<br />color: black_gesso\",\"season: 18<br />count:  5<br />color: black_gesso\",\"season: 19<br />count:  4<br />color: black_gesso\",\"season: 20<br />count:  2<br />color: black_gesso\",\"season: 21<br />count:  6<br />color: black_gesso\",\"season: 22<br />count:  3<br />color: black_gesso\",\"season: 23<br />count:  4<br />color: black_gesso\",\"season: 24<br />count:  6<br />color: black_gesso\",\"season: 25<br />count:  6<br />color: black_gesso\",\"season: 26<br />count:  5<br />color: black_gesso\",\"season: 27<br />count:  3<br />color: black_gesso\",\"season: 28<br />count:  3<br />color: black_gesso\",\"season: 29<br />count:  3<br />color: black_gesso\",\"season: 30<br />count:  5<br />color: black_gesso\",\"season: 31<br />count:  3<br />color: black_gesso\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"black_gesso\",\"legendgroup\":\"black_gesso\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[69,119,104,105,90,108,100,110,111,121,105,120,116,130,120,108,122,118,118,120,119,124,115,110,116,111,107,106,111,122,117],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[10,11,9,11,7,12,12,13,13,13,10,12,8,10,10,10,13,11,10,11,9,11,10,9,10,9,8,11,10,9,9],\"text\":[\"season:  1<br />count: 10<br />color: bright_red\",\"season:  2<br />count: 11<br />color: bright_red\",\"season:  3<br />count:  9<br />color: bright_red\",\"season:  4<br />count: 11<br />color: bright_red\",\"season:  5<br />count:  7<br />color: bright_red\",\"season:  6<br />count: 12<br />color: bright_red\",\"season:  7<br />count: 12<br />color: bright_red\",\"season:  8<br />count: 13<br />color: bright_red\",\"season:  9<br />count: 13<br />color: bright_red\",\"season: 10<br />count: 13<br />color: bright_red\",\"season: 11<br />count: 10<br />color: bright_red\",\"season: 12<br />count: 12<br />color: bright_red\",\"season: 13<br />count:  8<br />color: bright_red\",\"season: 14<br />count: 10<br />color: bright_red\",\"season: 15<br />count: 10<br />color: bright_red\",\"season: 16<br />count: 10<br />color: bright_red\",\"season: 17<br />count: 13<br />color: bright_red\",\"season: 18<br />count: 11<br />color: bright_red\",\"season: 19<br />count: 10<br />color: bright_red\",\"season: 20<br />count: 11<br />color: bright_red\",\"season: 21<br />count:  9<br />color: bright_red\",\"season: 22<br />count: 11<br />color: bright_red\",\"season: 23<br />count: 10<br />color: bright_red\",\"season: 24<br />count:  9<br />color: bright_red\",\"season: 25<br />count: 10<br />color: bright_red\",\"season: 26<br />count:  9<br />color: bright_red\",\"season: 27<br />count:  8<br />color: bright_red\",\"season: 28<br />count: 11<br />color: bright_red\",\"season: 29<br />count: 10<br />color: bright_red\",\"season: 30<br />count:  9<br />color: bright_red\",\"season: 31<br />count:  9<br />color: bright_red\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(219,0,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"bright_red\",\"legendgroup\":\"bright_red\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[69,108,93,94,80,96,100,110,111,121,105,120,116,130,120,108,122,118,118,120,119,124,115,110,116,111,107,106,111,122,117],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[0,11,11,11,10,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"text\":[\"season:  1<br />count:  0<br />color: burnt_umber\",\"season:  2<br />count: 11<br />color: burnt_umber\",\"season:  3<br />count: 11<br />color: burnt_umber\",\"season:  4<br />count: 11<br />color: burnt_umber\",\"season:  5<br />count: 10<br />color: burnt_umber\",\"season:  6<br />count: 12<br />color: burnt_umber\",\"season:  7<br />count:  0<br />color: burnt_umber\",\"season:  8<br />count:  0<br />color: burnt_umber\",\"season:  9<br />count:  0<br />color: burnt_umber\",\"season: 10<br />count:  0<br />color: burnt_umber\",\"season: 11<br />count:  0<br />color: burnt_umber\",\"season: 12<br />count:  0<br />color: burnt_umber\",\"season: 13<br />count:  0<br />color: burnt_umber\",\"season: 14<br />count:  0<br />color: burnt_umber\",\"season: 15<br />count:  0<br />color: burnt_umber\",\"season: 16<br />count:  0<br />color: burnt_umber\",\"season: 17<br />count:  0<br />color: burnt_umber\",\"season: 18<br />count:  0<br />color: burnt_umber\",\"season: 19<br />count:  0<br />color: burnt_umber\",\"season: 20<br />count:  0<br />color: burnt_umber\",\"season: 21<br />count:  0<br />color: burnt_umber\",\"season: 22<br />count:  0<br />color: burnt_umber\",\"season: 23<br />count:  0<br />color: burnt_umber\",\"season: 24<br />count:  0<br />color: burnt_umber\",\"season: 25<br />count:  0<br />color: burnt_umber\",\"season: 26<br />count:  0<br />color: burnt_umber\",\"season: 27<br />count:  0<br />color: burnt_umber\",\"season: 28<br />count:  0<br />color: burnt_umber\",\"season: 29<br />count:  0<br />color: burnt_umber\",\"season: 30<br />count:  0<br />color: burnt_umber\",\"season: 31<br />count:  0<br />color: burnt_umber\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(138,51,36,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"burnt_umber\",\"legendgroup\":\"burnt_umber\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[59,96,80,82,72,83,90,98,100,109,95,108,104,118,108,97,109,106,106,109,108,112,104,101,104,100,97,95,102,111,108],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[10,12,13,12,8,13,10,12,11,12,10,12,12,12,12,11,13,12,12,11,11,12,11,9,12,11,10,11,9,11,9],\"text\":[\"season:  1<br />count: 10<br />color: carmium_yellow\",\"season:  2<br />count: 12<br />color: carmium_yellow\",\"season:  3<br />count: 13<br />color: carmium_yellow\",\"season:  4<br />count: 12<br />color: carmium_yellow\",\"season:  5<br />count:  8<br />color: carmium_yellow\",\"season:  6<br />count: 13<br />color: carmium_yellow\",\"season:  7<br />count: 10<br />color: carmium_yellow\",\"season:  8<br />count: 12<br />color: carmium_yellow\",\"season:  9<br />count: 11<br />color: carmium_yellow\",\"season: 10<br />count: 12<br />color: carmium_yellow\",\"season: 11<br />count: 10<br />color: carmium_yellow\",\"season: 12<br />count: 12<br />color: carmium_yellow\",\"season: 13<br />count: 12<br />color: carmium_yellow\",\"season: 14<br />count: 12<br />color: carmium_yellow\",\"season: 15<br />count: 12<br />color: carmium_yellow\",\"season: 16<br />count: 11<br />color: carmium_yellow\",\"season: 17<br />count: 13<br />color: carmium_yellow\",\"season: 18<br />count: 12<br />color: carmium_yellow\",\"season: 19<br />count: 12<br />color: carmium_yellow\",\"season: 20<br />count: 11<br />color: carmium_yellow\",\"season: 21<br />count: 11<br />color: carmium_yellow\",\"season: 22<br />count: 12<br />color: carmium_yellow\",\"season: 23<br />count: 11<br />color: carmium_yellow\",\"season: 24<br />count:  9<br />color: carmium_yellow\",\"season: 25<br />count: 12<br />color: carmium_yellow\",\"season: 26<br />count: 11<br />color: carmium_yellow\",\"season: 27<br />count: 10<br />color: carmium_yellow\",\"season: 28<br />count: 11<br />color: carmium_yellow\",\"season: 29<br />count:  9<br />color: carmium_yellow\",\"season: 30<br />count: 11<br />color: carmium_yellow\",\"season: 31<br />count:  9<br />color: carmium_yellow\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(255,236,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"carmium_yellow\",\"legendgroup\":\"carmium_yellow\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[59,96,80,82,72,83,80,87,87,96,82,96,91,105,95,86,96,93,93,96,97,99,92,95,92,90,88,89,91,98,95],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[0,0,0,0,0,0,10,11,13,13,13,12,13,13,13,11,13,13,13,13,11,13,12,6,12,10,9,6,11,13,13],\"text\":[\"season:  1<br />count:  0<br />color: dark_sienna\",\"season:  2<br />count:  0<br />color: dark_sienna\",\"season:  3<br />count:  0<br />color: dark_sienna\",\"season:  4<br />count:  0<br />color: dark_sienna\",\"season:  5<br />count:  0<br />color: dark_sienna\",\"season:  6<br />count:  0<br />color: dark_sienna\",\"season:  7<br />count: 10<br />color: dark_sienna\",\"season:  8<br />count: 11<br />color: dark_sienna\",\"season:  9<br />count: 13<br />color: dark_sienna\",\"season: 10<br />count: 13<br />color: dark_sienna\",\"season: 11<br />count: 13<br />color: dark_sienna\",\"season: 12<br />count: 12<br />color: dark_sienna\",\"season: 13<br />count: 13<br />color: dark_sienna\",\"season: 14<br />count: 13<br />color: dark_sienna\",\"season: 15<br />count: 13<br />color: dark_sienna\",\"season: 16<br />count: 11<br />color: dark_sienna\",\"season: 17<br />count: 13<br />color: dark_sienna\",\"season: 18<br />count: 13<br />color: dark_sienna\",\"season: 19<br />count: 13<br />color: dark_sienna\",\"season: 20<br />count: 13<br />color: dark_sienna\",\"season: 21<br />count: 11<br />color: dark_sienna\",\"season: 22<br />count: 13<br />color: dark_sienna\",\"season: 23<br />count: 12<br />color: dark_sienna\",\"season: 24<br />count:  6<br />color: dark_sienna\",\"season: 25<br />count: 12<br />color: dark_sienna\",\"season: 26<br />count: 10<br />color: dark_sienna\",\"season: 27<br />count:  9<br />color: dark_sienna\",\"season: 28<br />count:  6<br />color: dark_sienna\",\"season: 29<br />count: 11<br />color: dark_sienna\",\"season: 30<br />count: 13<br />color: dark_sienna\",\"season: 31<br />count: 13<br />color: dark_sienna\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(95,46,31,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"dark_sienna\",\"legendgroup\":\"dark_sienna\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[59,96,80,82,72,83,80,87,87,96,82,96,91,105,95,86,96,93,93,96,97,98,92,95,92,90,88,89,91,98,95],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],\"text\":[\"season:  1<br />count:  0<br />color: indian_red\",\"season:  2<br />count:  0<br />color: indian_red\",\"season:  3<br />count:  0<br />color: indian_red\",\"season:  4<br />count:  0<br />color: indian_red\",\"season:  5<br />count:  0<br />color: indian_red\",\"season:  6<br />count:  0<br />color: indian_red\",\"season:  7<br />count:  0<br />color: indian_red\",\"season:  8<br />count:  0<br />color: indian_red\",\"season:  9<br />count:  0<br />color: indian_red\",\"season: 10<br />count:  0<br />color: indian_red\",\"season: 11<br />count:  0<br />color: indian_red\",\"season: 12<br />count:  0<br />color: indian_red\",\"season: 13<br />count:  0<br />color: indian_red\",\"season: 14<br />count:  0<br />color: indian_red\",\"season: 15<br />count:  0<br />color: indian_red\",\"season: 16<br />count:  0<br />color: indian_red\",\"season: 17<br />count:  0<br />color: indian_red\",\"season: 18<br />count:  0<br />color: indian_red\",\"season: 19<br />count:  0<br />color: indian_red\",\"season: 20<br />count:  0<br />color: indian_red\",\"season: 21<br />count:  0<br />color: indian_red\",\"season: 22<br />count:  1<br />color: indian_red\",\"season: 23<br />count:  0<br />color: indian_red\",\"season: 24<br />count:  0<br />color: indian_red\",\"season: 25<br />count:  0<br />color: indian_red\",\"season: 26<br />count:  0<br />color: indian_red\",\"season: 27<br />count:  0<br />color: indian_red\",\"season: 28<br />count:  0<br />color: indian_red\",\"season: 29<br />count:  0<br />color: indian_red\",\"season: 30<br />count:  0<br />color: indian_red\",\"season: 31<br />count:  0<br />color: indian_red\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(205,92,92,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"indian_red\",\"legendgroup\":\"indian_red\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[59,87,75,72,62,71,70,75,79,86,73,85,82,93,86,76,86,83,85,84,86,87,84,87,81,80,79,79,83,87,86],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[0,9,5,10,10,12,10,12,8,10,9,11,9,12,9,10,10,10,8,12,11,11,8,8,11,10,9,10,8,11,9],\"text\":[\"season:  1<br />count:  0<br />color: indian_yellow\",\"season:  2<br />count:  9<br />color: indian_yellow\",\"season:  3<br />count:  5<br />color: indian_yellow\",\"season:  4<br />count: 10<br />color: indian_yellow\",\"season:  5<br />count: 10<br />color: indian_yellow\",\"season:  6<br />count: 12<br />color: indian_yellow\",\"season:  7<br />count: 10<br />color: indian_yellow\",\"season:  8<br />count: 12<br />color: indian_yellow\",\"season:  9<br />count:  8<br />color: indian_yellow\",\"season: 10<br />count: 10<br />color: indian_yellow\",\"season: 11<br />count:  9<br />color: indian_yellow\",\"season: 12<br />count: 11<br />color: indian_yellow\",\"season: 13<br />count:  9<br />color: indian_yellow\",\"season: 14<br />count: 12<br />color: indian_yellow\",\"season: 15<br />count:  9<br />color: indian_yellow\",\"season: 16<br />count: 10<br />color: indian_yellow\",\"season: 17<br />count: 10<br />color: indian_yellow\",\"season: 18<br />count: 10<br />color: indian_yellow\",\"season: 19<br />count:  8<br />color: indian_yellow\",\"season: 20<br />count: 12<br />color: indian_yellow\",\"season: 21<br />count: 11<br />color: indian_yellow\",\"season: 22<br />count: 11<br />color: indian_yellow\",\"season: 23<br />count:  8<br />color: indian_yellow\",\"season: 24<br />count:  8<br />color: indian_yellow\",\"season: 25<br />count: 11<br />color: indian_yellow\",\"season: 26<br />count: 10<br />color: indian_yellow\",\"season: 27<br />count:  9<br />color: indian_yellow\",\"season: 28<br />count: 10<br />color: indian_yellow\",\"season: 29<br />count:  8<br />color: indian_yellow\",\"season: 30<br />count: 11<br />color: indian_yellow\",\"season: 31<br />count:  9<br />color: indian_yellow\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(255,184,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"indian_yellow\",\"legendgroup\":\"indian_yellow\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[59,87,74,71,60,71,69,75,79,86,73,84,82,92,86,76,86,81,85,84,86,87,84,87,81,80,76,79,83,87,84],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[0,0,1,1,2,0,1,0,0,0,0,1,0,1,0,0,0,2,0,0,0,0,0,0,0,0,3,0,0,0,2],\"text\":[\"season:  1<br />count:  0<br />color: liquid_black\",\"season:  2<br />count:  0<br />color: liquid_black\",\"season:  3<br />count:  1<br />color: liquid_black\",\"season:  4<br />count:  1<br />color: liquid_black\",\"season:  5<br />count:  2<br />color: liquid_black\",\"season:  6<br />count:  0<br />color: liquid_black\",\"season:  7<br />count:  1<br />color: liquid_black\",\"season:  8<br />count:  0<br />color: liquid_black\",\"season:  9<br />count:  0<br />color: liquid_black\",\"season: 10<br />count:  0<br />color: liquid_black\",\"season: 11<br />count:  0<br />color: liquid_black\",\"season: 12<br />count:  1<br />color: liquid_black\",\"season: 13<br />count:  0<br />color: liquid_black\",\"season: 14<br />count:  1<br />color: liquid_black\",\"season: 15<br />count:  0<br />color: liquid_black\",\"season: 16<br />count:  0<br />color: liquid_black\",\"season: 17<br />count:  0<br />color: liquid_black\",\"season: 18<br />count:  2<br />color: liquid_black\",\"season: 19<br />count:  0<br />color: liquid_black\",\"season: 20<br />count:  0<br />color: liquid_black\",\"season: 21<br />count:  0<br />color: liquid_black\",\"season: 22<br />count:  0<br />color: liquid_black\",\"season: 23<br />count:  0<br />color: liquid_black\",\"season: 24<br />count:  0<br />color: liquid_black\",\"season: 25<br />count:  0<br />color: liquid_black\",\"season: 26<br />count:  0<br />color: liquid_black\",\"season: 27<br />count:  3<br />color: liquid_black\",\"season: 28<br />count:  0<br />color: liquid_black\",\"season: 29<br />count:  0<br />color: liquid_black\",\"season: 30<br />count:  0<br />color: liquid_black\",\"season: 31<br />count:  2<br />color: liquid_black\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"liquid_black\",\"legendgroup\":\"liquid_black\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[59,87,74,71,59,71,69,75,77,85,71,82,82,92,85,76,84,80,81,82,81,86,83,83,79,78,68,77,81,83,82],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[0,0,0,0,1,0,0,0,2,1,2,2,0,0,1,0,2,1,4,2,5,1,1,4,2,2,8,2,2,4,2],\"text\":[\"season:  1<br />count:  0<br />color: liquid_clear\",\"season:  2<br />count:  0<br />color: liquid_clear\",\"season:  3<br />count:  0<br />color: liquid_clear\",\"season:  4<br />count:  0<br />color: liquid_clear\",\"season:  5<br />count:  1<br />color: liquid_clear\",\"season:  6<br />count:  0<br />color: liquid_clear\",\"season:  7<br />count:  0<br />color: liquid_clear\",\"season:  8<br />count:  0<br />color: liquid_clear\",\"season:  9<br />count:  2<br />color: liquid_clear\",\"season: 10<br />count:  1<br />color: liquid_clear\",\"season: 11<br />count:  2<br />color: liquid_clear\",\"season: 12<br />count:  2<br />color: liquid_clear\",\"season: 13<br />count:  0<br />color: liquid_clear\",\"season: 14<br />count:  0<br />color: liquid_clear\",\"season: 15<br />count:  1<br />color: liquid_clear\",\"season: 16<br />count:  0<br />color: liquid_clear\",\"season: 17<br />count:  2<br />color: liquid_clear\",\"season: 18<br />count:  1<br />color: liquid_clear\",\"season: 19<br />count:  4<br />color: liquid_clear\",\"season: 20<br />count:  2<br />color: liquid_clear\",\"season: 21<br />count:  5<br />color: liquid_clear\",\"season: 22<br />count:  1<br />color: liquid_clear\",\"season: 23<br />count:  1<br />color: liquid_clear\",\"season: 24<br />count:  4<br />color: liquid_clear\",\"season: 25<br />count:  2<br />color: liquid_clear\",\"season: 26<br />count:  2<br />color: liquid_clear\",\"season: 27<br />count:  8<br />color: liquid_clear\",\"season: 28<br />count:  2<br />color: liquid_clear\",\"season: 29<br />count:  2<br />color: liquid_clear\",\"season: 30<br />count:  4<br />color: liquid_clear\",\"season: 31<br />count:  2<br />color: liquid_clear\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(255,255,255,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"liquid_clear\",\"legendgroup\":\"liquid_clear\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[59,87,73,70,59,71,60,63,64,72,59,69,69,79,72,64,71,67,68,69,68,73,70,70,67,66,55,65,68,70,69],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[0,0,1,1,0,0,9,12,13,13,12,13,13,13,13,12,13,13,13,13,13,13,13,13,12,12,13,12,13,13,13],\"text\":[\"season:  1<br />count:  0<br />color: midnight_black\",\"season:  2<br />count:  0<br />color: midnight_black\",\"season:  3<br />count:  1<br />color: midnight_black\",\"season:  4<br />count:  1<br />color: midnight_black\",\"season:  5<br />count:  0<br />color: midnight_black\",\"season:  6<br />count:  0<br />color: midnight_black\",\"season:  7<br />count:  9<br />color: midnight_black\",\"season:  8<br />count: 12<br />color: midnight_black\",\"season:  9<br />count: 13<br />color: midnight_black\",\"season: 10<br />count: 13<br />color: midnight_black\",\"season: 11<br />count: 12<br />color: midnight_black\",\"season: 12<br />count: 13<br />color: midnight_black\",\"season: 13<br />count: 13<br />color: midnight_black\",\"season: 14<br />count: 13<br />color: midnight_black\",\"season: 15<br />count: 13<br />color: midnight_black\",\"season: 16<br />count: 12<br />color: midnight_black\",\"season: 17<br />count: 13<br />color: midnight_black\",\"season: 18<br />count: 13<br />color: midnight_black\",\"season: 19<br />count: 13<br />color: midnight_black\",\"season: 20<br />count: 13<br />color: midnight_black\",\"season: 21<br />count: 13<br />color: midnight_black\",\"season: 22<br />count: 13<br />color: midnight_black\",\"season: 23<br />count: 13<br />color: midnight_black\",\"season: 24<br />count: 13<br />color: midnight_black\",\"season: 25<br />count: 12<br />color: midnight_black\",\"season: 26<br />count: 12<br />color: midnight_black\",\"season: 27<br />count: 13<br />color: midnight_black\",\"season: 28<br />count: 12<br />color: midnight_black\",\"season: 29<br />count: 13<br />color: midnight_black\",\"season: 30<br />count: 13<br />color: midnight_black\",\"season: 31<br />count: 13<br />color: midnight_black\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"midnight_black\",\"legendgroup\":\"midnight_black\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[59,75,65,60,49,60,51,52,51,59,52,58,58,66,60,53,58,54,56,56,56,61,61,58,62,57,48,52,58,61,57],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[0,12,8,10,10,11,9,11,13,13,7,11,11,13,12,11,13,13,12,13,12,12,9,12,5,9,7,13,10,9,12],\"text\":[\"season:  1<br />count:  0<br />color: phthalo_blue\",\"season:  2<br />count: 12<br />color: phthalo_blue\",\"season:  3<br />count:  8<br />color: phthalo_blue\",\"season:  4<br />count: 10<br />color: phthalo_blue\",\"season:  5<br />count: 10<br />color: phthalo_blue\",\"season:  6<br />count: 11<br />color: phthalo_blue\",\"season:  7<br />count:  9<br />color: phthalo_blue\",\"season:  8<br />count: 11<br />color: phthalo_blue\",\"season:  9<br />count: 13<br />color: phthalo_blue\",\"season: 10<br />count: 13<br />color: phthalo_blue\",\"season: 11<br />count:  7<br />color: phthalo_blue\",\"season: 12<br />count: 11<br />color: phthalo_blue\",\"season: 13<br />count: 11<br />color: phthalo_blue\",\"season: 14<br />count: 13<br />color: phthalo_blue\",\"season: 15<br />count: 12<br />color: phthalo_blue\",\"season: 16<br />count: 11<br />color: phthalo_blue\",\"season: 17<br />count: 13<br />color: phthalo_blue\",\"season: 18<br />count: 13<br />color: phthalo_blue\",\"season: 19<br />count: 12<br />color: phthalo_blue\",\"season: 20<br />count: 13<br />color: phthalo_blue\",\"season: 21<br />count: 12<br />color: phthalo_blue\",\"season: 22<br />count: 12<br />color: phthalo_blue\",\"season: 23<br />count:  9<br />color: phthalo_blue\",\"season: 24<br />count: 12<br />color: phthalo_blue\",\"season: 25<br />count:  5<br />color: phthalo_blue\",\"season: 26<br />count:  9<br />color: phthalo_blue\",\"season: 27<br />count:  7<br />color: phthalo_blue\",\"season: 28<br />count: 13<br />color: phthalo_blue\",\"season: 29<br />count: 10<br />color: phthalo_blue\",\"season: 30<br />count:  9<br />color: phthalo_blue\",\"season: 31<br />count: 12<br />color: phthalo_blue\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(12,0,64,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"phthalo_blue\",\"legendgroup\":\"phthalo_blue\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[49,63,57,53,43,54,47,49,50,57,52,55,55,61,58,51,56,53,54,54,53,58,57,53,60,53,45,50,54,59,54],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[10,12,8,7,6,6,4,3,1,2,0,3,3,5,2,2,2,1,2,2,3,3,4,5,2,4,3,2,4,2,3],\"text\":[\"season:  1<br />count: 10<br />color: phthalo_green\",\"season:  2<br />count: 12<br />color: phthalo_green\",\"season:  3<br />count:  8<br />color: phthalo_green\",\"season:  4<br />count:  7<br />color: phthalo_green\",\"season:  5<br />count:  6<br />color: phthalo_green\",\"season:  6<br />count:  6<br />color: phthalo_green\",\"season:  7<br />count:  4<br />color: phthalo_green\",\"season:  8<br />count:  3<br />color: phthalo_green\",\"season:  9<br />count:  1<br />color: phthalo_green\",\"season: 10<br />count:  2<br />color: phthalo_green\",\"season: 11<br />count:  0<br />color: phthalo_green\",\"season: 12<br />count:  3<br />color: phthalo_green\",\"season: 13<br />count:  3<br />color: phthalo_green\",\"season: 14<br />count:  5<br />color: phthalo_green\",\"season: 15<br />count:  2<br />color: phthalo_green\",\"season: 16<br />count:  2<br />color: phthalo_green\",\"season: 17<br />count:  2<br />color: phthalo_green\",\"season: 18<br />count:  1<br />color: phthalo_green\",\"season: 19<br />count:  2<br />color: phthalo_green\",\"season: 20<br />count:  2<br />color: phthalo_green\",\"season: 21<br />count:  3<br />color: phthalo_green\",\"season: 22<br />count:  3<br />color: phthalo_green\",\"season: 23<br />count:  4<br />color: phthalo_green\",\"season: 24<br />count:  5<br />color: phthalo_green\",\"season: 25<br />count:  2<br />color: phthalo_green\",\"season: 26<br />count:  4<br />color: phthalo_green\",\"season: 27<br />count:  3<br />color: phthalo_green\",\"season: 28<br />count:  2<br />color: phthalo_green\",\"season: 29<br />count:  4<br />color: phthalo_green\",\"season: 30<br />count:  2<br />color: phthalo_green\",\"season: 31<br />count:  3<br />color: phthalo_green\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(16,46,60,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"phthalo_green\",\"legendgroup\":\"phthalo_green\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[36,50,48,44,39,49,43,46,46,46,43,46,47,50,46,46,49,48,45,48,46,49,45,41,49,42,38,42,44,48,45],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[13,13,9,9,4,5,4,3,4,11,9,9,8,11,12,5,7,5,9,6,7,9,12,12,11,11,7,8,10,11,9],\"text\":[\"season:  1<br />count: 13<br />color: prussian_blue\",\"season:  2<br />count: 13<br />color: prussian_blue\",\"season:  3<br />count:  9<br />color: prussian_blue\",\"season:  4<br />count:  9<br />color: prussian_blue\",\"season:  5<br />count:  4<br />color: prussian_blue\",\"season:  6<br />count:  5<br />color: prussian_blue\",\"season:  7<br />count:  4<br />color: prussian_blue\",\"season:  8<br />count:  3<br />color: prussian_blue\",\"season:  9<br />count:  4<br />color: prussian_blue\",\"season: 10<br />count: 11<br />color: prussian_blue\",\"season: 11<br />count:  9<br />color: prussian_blue\",\"season: 12<br />count:  9<br />color: prussian_blue\",\"season: 13<br />count:  8<br />color: prussian_blue\",\"season: 14<br />count: 11<br />color: prussian_blue\",\"season: 15<br />count: 12<br />color: prussian_blue\",\"season: 16<br />count:  5<br />color: prussian_blue\",\"season: 17<br />count:  7<br />color: prussian_blue\",\"season: 18<br />count:  5<br />color: prussian_blue\",\"season: 19<br />count:  9<br />color: prussian_blue\",\"season: 20<br />count:  6<br />color: prussian_blue\",\"season: 21<br />count:  7<br />color: prussian_blue\",\"season: 22<br />count:  9<br />color: prussian_blue\",\"season: 23<br />count: 12<br />color: prussian_blue\",\"season: 24<br />count: 12<br />color: prussian_blue\",\"season: 25<br />count: 11<br />color: prussian_blue\",\"season: 26<br />count: 11<br />color: prussian_blue\",\"season: 27<br />count:  7<br />color: prussian_blue\",\"season: 28<br />count:  8<br />color: prussian_blue\",\"season: 29<br />count: 10<br />color: prussian_blue\",\"season: 30<br />count: 11<br />color: prussian_blue\",\"season: 31<br />count:  9<br />color: prussian_blue\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(2,30,68,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"prussian_blue\",\"legendgroup\":\"prussian_blue\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[26,38,37,34,30,38,34,38,38,37,35,37,37,39,37,36,39,37,38,37,36,38,37,29,37,32,31,30,33,37,36],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[10,12,11,10,9,11,9,8,8,9,8,9,10,11,9,10,10,11,7,11,10,11,8,12,12,10,7,12,11,11,9],\"text\":[\"season:  1<br />count: 10<br />color: sap_green\",\"season:  2<br />count: 12<br />color: sap_green\",\"season:  3<br />count: 11<br />color: sap_green\",\"season:  4<br />count: 10<br />color: sap_green\",\"season:  5<br />count:  9<br />color: sap_green\",\"season:  6<br />count: 11<br />color: sap_green\",\"season:  7<br />count:  9<br />color: sap_green\",\"season:  8<br />count:  8<br />color: sap_green\",\"season:  9<br />count:  8<br />color: sap_green\",\"season: 10<br />count:  9<br />color: sap_green\",\"season: 11<br />count:  8<br />color: sap_green\",\"season: 12<br />count:  9<br />color: sap_green\",\"season: 13<br />count: 10<br />color: sap_green\",\"season: 14<br />count: 11<br />color: sap_green\",\"season: 15<br />count:  9<br />color: sap_green\",\"season: 16<br />count: 10<br />color: sap_green\",\"season: 17<br />count: 10<br />color: sap_green\",\"season: 18<br />count: 11<br />color: sap_green\",\"season: 19<br />count:  7<br />color: sap_green\",\"season: 20<br />count: 11<br />color: sap_green\",\"season: 21<br />count: 10<br />color: sap_green\",\"season: 22<br />count: 11<br />color: sap_green\",\"season: 23<br />count:  8<br />color: sap_green\",\"season: 24<br />count: 12<br />color: sap_green\",\"season: 25<br />count: 12<br />color: sap_green\",\"season: 26<br />count: 10<br />color: sap_green\",\"season: 27<br />count:  7<br />color: sap_green\",\"season: 28<br />count: 12<br />color: sap_green\",\"season: 29<br />count: 11<br />color: sap_green\",\"season: 30<br />count: 11<br />color: sap_green\",\"season: 31<br />count:  9<br />color: sap_green\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(10,52,16,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"sap_green\",\"legendgroup\":\"sap_green\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[13,25,25,21,17,25,21,25,25,24,22,24,24,26,24,24,26,24,25,24,23,25,24,16,24,19,18,17,21,24,23],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[13,13,12,13,13,13,13,13,13,13,13,13,13,13,13,12,13,13,13,13,13,13,13,13,13,13,13,13,12,13,13],\"text\":[\"season:  1<br />count: 13<br />color: titanium_white\",\"season:  2<br />count: 13<br />color: titanium_white\",\"season:  3<br />count: 12<br />color: titanium_white\",\"season:  4<br />count: 13<br />color: titanium_white\",\"season:  5<br />count: 13<br />color: titanium_white\",\"season:  6<br />count: 13<br />color: titanium_white\",\"season:  7<br />count: 13<br />color: titanium_white\",\"season:  8<br />count: 13<br />color: titanium_white\",\"season:  9<br />count: 13<br />color: titanium_white\",\"season: 10<br />count: 13<br />color: titanium_white\",\"season: 11<br />count: 13<br />color: titanium_white\",\"season: 12<br />count: 13<br />color: titanium_white\",\"season: 13<br />count: 13<br />color: titanium_white\",\"season: 14<br />count: 13<br />color: titanium_white\",\"season: 15<br />count: 13<br />color: titanium_white\",\"season: 16<br />count: 12<br />color: titanium_white\",\"season: 17<br />count: 13<br />color: titanium_white\",\"season: 18<br />count: 13<br />color: titanium_white\",\"season: 19<br />count: 13<br />color: titanium_white\",\"season: 20<br />count: 13<br />color: titanium_white\",\"season: 21<br />count: 13<br />color: titanium_white\",\"season: 22<br />count: 13<br />color: titanium_white\",\"season: 23<br />count: 13<br />color: titanium_white\",\"season: 24<br />count: 13<br />color: titanium_white\",\"season: 25<br />count: 13<br />color: titanium_white\",\"season: 26<br />count: 13<br />color: titanium_white\",\"season: 27<br />count: 13<br />color: titanium_white\",\"season: 28<br />count: 13<br />color: titanium_white\",\"season: 29<br />count: 12<br />color: titanium_white\",\"season: 30<br />count: 13<br />color: titanium_white\",\"season: 31<br />count: 13<br />color: titanium_white\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(255,255,255,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"titanium_white\",\"legendgroup\":\"titanium_white\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[0,12,12,9,7,12,11,12,12,11,9,11,11,13,11,11,13,11,12,12,12,12,11,10,12,9,8,11,9,11,10],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[13,13,13,12,10,13,10,13,13,13,13,13,13,13,13,13,13,13,13,12,11,13,13,6,12,10,10,6,12,13,13],\"text\":[\"season:  1<br />count: 13<br />color: van_dyke_brown\",\"season:  2<br />count: 13<br />color: van_dyke_brown\",\"season:  3<br />count: 13<br />color: van_dyke_brown\",\"season:  4<br />count: 12<br />color: van_dyke_brown\",\"season:  5<br />count: 10<br />color: van_dyke_brown\",\"season:  6<br />count: 13<br />color: van_dyke_brown\",\"season:  7<br />count: 10<br />color: van_dyke_brown\",\"season:  8<br />count: 13<br />color: van_dyke_brown\",\"season:  9<br />count: 13<br />color: van_dyke_brown\",\"season: 10<br />count: 13<br />color: van_dyke_brown\",\"season: 11<br />count: 13<br />color: van_dyke_brown\",\"season: 12<br />count: 13<br />color: van_dyke_brown\",\"season: 13<br />count: 13<br />color: van_dyke_brown\",\"season: 14<br />count: 13<br />color: van_dyke_brown\",\"season: 15<br />count: 13<br />color: van_dyke_brown\",\"season: 16<br />count: 13<br />color: van_dyke_brown\",\"season: 17<br />count: 13<br />color: van_dyke_brown\",\"season: 18<br />count: 13<br />color: van_dyke_brown\",\"season: 19<br />count: 13<br />color: van_dyke_brown\",\"season: 20<br />count: 12<br />color: van_dyke_brown\",\"season: 21<br />count: 11<br />color: van_dyke_brown\",\"season: 22<br />count: 13<br />color: van_dyke_brown\",\"season: 23<br />count: 13<br />color: van_dyke_brown\",\"season: 24<br />count:  6<br />color: van_dyke_brown\",\"season: 25<br />count: 12<br />color: van_dyke_brown\",\"season: 26<br />count: 10<br />color: van_dyke_brown\",\"season: 27<br />count: 10<br />color: van_dyke_brown\",\"season: 28<br />count:  6<br />color: van_dyke_brown\",\"season: 29<br />count: 12<br />color: van_dyke_brown\",\"season: 30<br />count: 13<br />color: van_dyke_brown\",\"season: 31<br />count: 13<br />color: van_dyke_brown\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(34,27,21,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"van_dyke_brown\",\"legendgroup\":\"van_dyke_brown\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],\"base\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],\"y\":[0,12,12,9,7,12,11,12,12,11,9,11,11,13,11,11,13,11,12,12,12,12,11,10,12,9,8,11,9,11,10],\"text\":[\"season:  1<br />count:  0<br />color: yellow_orchre\",\"season:  2<br />count: 12<br />color: yellow_orchre\",\"season:  3<br />count: 12<br />color: yellow_orchre\",\"season:  4<br />count:  9<br />color: yellow_orchre\",\"season:  5<br />count:  7<br />color: yellow_orchre\",\"season:  6<br />count: 12<br />color: yellow_orchre\",\"season:  7<br />count: 11<br />color: yellow_orchre\",\"season:  8<br />count: 12<br />color: yellow_orchre\",\"season:  9<br />count: 12<br />color: yellow_orchre\",\"season: 10<br />count: 11<br />color: yellow_orchre\",\"season: 11<br />count:  9<br />color: yellow_orchre\",\"season: 12<br />count: 11<br />color: yellow_orchre\",\"season: 13<br />count: 11<br />color: yellow_orchre\",\"season: 14<br />count: 13<br />color: yellow_orchre\",\"season: 15<br />count: 11<br />color: yellow_orchre\",\"season: 16<br />count: 11<br />color: yellow_orchre\",\"season: 17<br />count: 13<br />color: yellow_orchre\",\"season: 18<br />count: 11<br />color: yellow_orchre\",\"season: 19<br />count: 12<br />color: yellow_orchre\",\"season: 20<br />count: 12<br />color: yellow_orchre\",\"season: 21<br />count: 12<br />color: yellow_orchre\",\"season: 22<br />count: 12<br />color: yellow_orchre\",\"season: 23<br />count: 11<br />color: yellow_orchre\",\"season: 24<br />count: 10<br />color: yellow_orchre\",\"season: 25<br />count: 12<br />color: yellow_orchre\",\"season: 26<br />count:  9<br />color: yellow_orchre\",\"season: 27<br />count:  8<br />color: yellow_orchre\",\"season: 28<br />count: 11<br />color: yellow_orchre\",\"season: 29<br />count:  9<br />color: yellow_orchre\",\"season: 30<br />count: 11<br />color: yellow_orchre\",\"season: 31<br />count: 10<br />color: yellow_orchre\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(199,155,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"yellow_orchre\",\"legendgroup\":\"yellow_orchre\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":43.7625570776256,\"r\":7.30593607305936,\"b\":40.1826484018265,\"l\":43.1050228310502},\"plot_bgcolor\":\"rgba(235,235,235,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"title\":{\"text\":\"Colors Used Each Season\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"Times\",\"size\":17.5342465753425},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.995,32.995],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"10\",\"20\",\"30\"],\"tickvals\":[1.11022302462516e-16,10,20,30],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"10\",\"20\",\"30\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Season\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"Times\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-7.8,163.8],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"50\",\"100\",\"150\"],\"tickvals\":[8.88178419700125e-16,50,100,150],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"50\",\"100\",\"150\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Colors Used\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"Times\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895},\"title\":{\"text\":\"color\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"57442f5cd78e\":{\"x\":{},\"y\":{},\"fill\":{},\"type\":\"bar\"}},\"cur_data\":\"57442f5cd78e\",\"visdat\":{\"57442f5cd78e\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n### Trends\n\n## Color Trends \n\n* <font color=\"#CD5C5C\"> **Indian Red** </font> is the color that is **least used**. It was only featured once in  season 22 episode 1 in the Painting _Autumn Images_ shown below. \n\n<center>\n\n![[Autumn Images](https://www.youtube.com/embed/HMx34Am6RFg) is a painting of a mountain in front <br>of big white clouds, and surrounded by trees. ](https://www.twoinchbrush.com/images/painting14.png)\n\n</center>\n\n* <font color=\"#8A3324\"> **Burnt Umber** </font> was only used in 55 episodes. The last painting it was used in was from season 6 episode 13 and is called _Blaze of Color_, shown below.\n\n<center>\n\n![[Blaze of Color](\thttps://www.youtube.com/embed/se7wOprxRGs) is a painting of a green and dark blue creek <br>surrounded by yellow and light green grass, trees, and <br>a vibrant blue, pink, yellow, orange, and red sunset. ](https://www.twoinchbrush.com/images/painting229.png)\n\n</center>\n\n* <font color=\"#5F2E1F\"> **Dark Sienna** </font> may have been used instead of Burnt umber. It can in the episode of the last season, season 31 episode 13, in a painting called _Wilderness Day_, shown below. \n\n<center>\n\n![[Wilderness Day](https://www.youtube.com/embed/nJGCVFn57U8) is a painting of a dark green meadow that includes <br>trees, bushes, and a misty mountain in the  background. ](https://www.twoinchbrush.com/images/painting411.png)\n\n</center>\n\nBelow is a graph that shows the number of time a color was used each season. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/print color trends graph-1.png){width=672}\n:::\n:::\n\n\n:::\n\n# Conclusion \n\n::: {.panel-tabset}\n\n### Results\n\n**Considering the use case of a viewer who is:**\n\n* New to painting.\n\n* Budget conscious.\n\n* Disappointed when spending money on something they hardly used.\n\n## My recommendations would be: \n\n1. Each season has the same amount of episodes, so the user might consider viewing the paintings from each season, and deciding which season's paintings they like best before selecting the color they will purchase. They will enjoy painting more if they know they will enjoy the end result. \n\n2. Season 1 uses the least amount of colors, and might be a good place to start for someone who is new to painting, and cannot otherwise decide which seasons paintings they enjoy the most. \n\n3. Consider using similar colors interchangeably, such as <font color=\"#5F2E1F\"> Dark Sienna </font> instead of <font color=\"#8A3324\"> Burnt Umber </font> and <font color=\"#CD5C5C\"> Indian Red </font>. The user might need to mix in more black or white, to get a similar result to the painting they are recreating, which is another thing to consider when purchasing supplies. \n\n### Discussion \n\n**What other questions would our given use case be curious about answering before investing their time into \"The Joy of Painting\"?**\n\n* Should they buy more of one paint (such as black and white) over others (such as purple)? \n\n* Is there any correlation between painting title and colors used? \n\n* What clusters of paintings use similar color palettes?\n\n**What are some other use cases for this data?**\n\n* An event planner who wants to pick one painting with the least amount of colors and complexity to paint with a group of people of varying experience levels. \n\n* An experienced painter who wants to wants to work with the most colors possible. \n\n* A homeowner who wants to recreate a painting with colors that will compliment their interier design choices. \n\n:::\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.6.0/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.1/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}