---
title: "NBA Salary 2023 Data Scraper"
---

```{r}
job_df_fun <- function(job_name, 
                       job_title,
                       job_website,
                       job_about,
                       job_description,
                       primary_responsibilites,
                       basic_qualifications,
                       ideal_qualifications){
  "
  This function ...
  "
  # save variables
  name <- job_name
  title <- job_title
  website <- job_website
  about <- job_about
  desc <- job_description
  prim_resp <- primary_responsibilites
  basic_qual <- basic_qualifications
  ideal_qual <- ideal_qualifications
  
  # create df
  df <- data.frame(name,
                   title,
                   website,
                   about,
                   desc,
                   prim_resp,
                   basic_qual,
                   ideal_qual)
  return(df)
}
```



```{r}
eab <- job_df_fun("EAB",
                  "Associate Data Scientist",
                  "https://eab.com/",
                  "At EAB , our mission is to make education smarter and our communities stronger. We work with more than 2,500 institutions to drive transformative change through data-driven insights and best-in-class capabilities. From kindergarten to college to career, EAB partners with leaders and practitioners to accelerate progress and drive results across five major areas: enrollment, student success, institutional strategy, data & analytics, and diversity, equity, and inclusion (DE&I). We work with each partner differently, tailoring our portfolio of research, technology, and marketing and enrollment solutions to meet the unique needs of every leadership team, as well as the students and employees they serve. At EAB, we serve not only our partner institutions but each other—that's why we are always working to make sure our employees love their jobs and are invested in their communities. See how we've been recognized for this dedication to our employees by checking out our recent awards .",
                  "EAB is seeking aspiring data scientists of diverse talents and interests to help grow our industry-leading software platform's artificial intelligence and machine learning capabilities. Whether you are by nature a researcher with a quantitative bent interested in tackling some of the most impactful questions in the social sciences, or a software engineer who wants to build a world-class machine learning platform, you can carve out a place for yourself on our team. We are a medium sized team working to discover, build, and scale AI/ML solutions that help colleges and universities support their students from the application phase to graduation and beyond in a positive, inquisitive, and collaborative environment.",
                  "1. Collaborate with data engineers and software engineers to integrate research-driven machine learning models into production software systems. 2. Build internal tools for data science/analytics workflows. 3. Manage data processing pipelines for analyzing terabyte-scale data from multiple sources. 4. Write Python and R code using current best practices. 5. Coordinate with product managers, software engineers, and customer-facing teams",
                  "1. Bachelor’s degree in a quantitative field, or equivalent experience. 2. Programming skills in Python or R. 3. Experience using SQL for data cleansing, transformation, summarization, or analysis. 4. Ability to communicate and collaborate with both technical and non-technical team members. 5. Conscientious, curious, dedicated, and quality-focused",
                  "1. Experience with machine learning, statistics, and the scientific method. 2. Professional experience with software engineering, data warehousing, Linux systems. 3. Experience with AWS or other cloud-based server management and machine learning services. 4. Commitment to valuing diversity, practicing inclusive behaviors, and contributing to an equitable working and continual learning environment in support of EAB’s DE&I Promise")
```


```{r}

```


```{r}
eab
```


