---
title: Decision Tree in R
---

# survial test in R

This is the ID3 algorithm

```{r}
install.packages("caret", dependencies = TRUE)
```




# Doesnt work 

This code is ... [](https://www.tutorialspoint.com/r/r_decision_tree.htm)

```{r}
library(ISLR)
# data(package="ISLR")
carseats<-Carseats
```


```{r}
require(tree)
```

```{r}
names(carseats)
```

```{r}
hist(carseats$Sales)
```

```{r}
High = ifelse(carseats$Sales<=8, "No", "Yes")
carseats = data.frame(carseats, High)
```

```{r}
tree.carseats = tree(High~.-Sales, data=carseats)
```

```{r}
summary(tree.carseats)
```




----

This code is based off the post [Decision Tree in R Programming](https://www.geeksforgeeks.org/decision-tree-in-r-programming/).

# Packages and Data

```{r}
# install.packages("rpart")
library(rpart)
```


```{r}
df <- head(df, 500)
pres_rate <- runif(500, min=0, max=1)
my_data <- data.frame(pres_rate,
                      df$dep_name,
                      df$age,
                      df$gender,
                      df$ethnicity,
                      df$employstatus,
                      df$insurance_status)
head(my_data)
```

```{r}
# install.packages("tree")
library(tree)
```



```{r}
mytree = tree(my_data$pres_rate~+my_data$df.dep_name+my_data$df.age+my_data$df.gender+my_data$df.ethnicity+my_data$df.employstatus+my_data$df.insurance_status,
              data = my_data)
summary(mytree)

mytree2 <- tree(Salary ~ Years + HmRun + Runs + RBI + Walks, data=Hitters)
summary(mytree2)

head(Hitters)
```

---

```{r}
library(ISLR)
library(rpart)
library(rpart.plot)

#build the initial decision tree
tree <- rpart(Salary ~ Years + HmRun, data=Hitters, control=rpart.control(cp=.0001))

#identify best cp value to use
best <- tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]

#produce a pruned tree based on the best cp value
pruned_tree <- prune(tree, cp=best)

#plot the pruned tree
prp(pruned_tree)
```

```{r}
#plot decision tree using custom arguments
prp(pruned_tree,
    faclen=0, #use full names for factor labels
    extra=1, #display number of observations for each terminal node
    roundint=F, #don't round to integers in output
    digits=5) #display 5 decimal places in output
```


```{r}
summary(pruned_tree)
```


