---
title: "Scrape Teams Function"
---

```{r}
library(rvest)
library(tidyverse)
```

This function works for basketball, and football (except the first row is column headers). Baseball might work, but needs more to work on, and hockey currently does not work. 

Note futeball is in Spanish, and the url changes. 

```{r}
scrape.teams <- function(sport){
  "
  This function ...
  "
  # save url
  url <- paste0("https://www.", sport,"-reference.com/teams/")

  # Read stats table
  div <- url %>%
  read_html %>%
  html_node("#all_teams_active") %>% 
  html_table()
  
  
  return(div)
}
```

This function

```{r}
# test <- scrape.teams("basketball")

t2 <- test %>% 
  subset(test$To == "2022-23") %>%
  filter(duplicated(Franchise) == FALSE)

team_names <- t2$Franchise
team_names
```

```{r}
team_n <- sub('\\w+ ',"", team_names)
team_n[[10]] <- "Warriors"
team_n[[13]] <- "Clippers"
team_n[[14]] <- "Lakers"
team_n[[19]] <- "Pelicans"
team_n[[20]] <- "Knicks"
team_n[[21]] <- "Thunder"
team_n[[25]] <- "Blazers"
team_n[[27]] <- "Spurs"
short_name <- team_n
long_name <- team_names
```


```{r}
team_slugs <- c("ATL", "BOS",
                "BRK", "CHO",
                "CHI", "CLE",
                "DAL", "DEN",
                "DET", "GSW",
                "HOU", "IND",
                "LAC", "LAL",
                "MEM", "MIA",
                "MIL", "MIN",
                "NOP", "NYK",
                "OKC", "ORL",
                "PHI", "PHO",
                "POR", "SAC",
                "SAS", "TOR",
                "UTA", "WAS")
```


```{r}
team_info <- data.frame(long_namez,
                        short_name, 
                        team_slugs)
team_info
```

```{r}
utils::write.csv(team_info, 
                 paste0("../00_data/",
                        base::Sys.Date(),
                        "_NBA_Team_Names_and_Slugs"))
```




