{
  "hash": "52cf342618e5e56644fec74b84a6fb99",
  "result": {
    "markdown": "---\ntitle: \"Statistics 451: Applied Statistics for Engineers and Scientists - Homework 1\"\nauthor: \"Randi Bolt\"\ndate: \"2021-06-28\"\ncategories: [Statistics]\ntoc: true\n---\n\n\nThe problems on this page are from Probability & Statistics for Engineering & Sciences 9th Edition by Jay L. Devore - Duxbury Publisher, and the work is mine.\n\n![](../../00_img/concreate-beams-flex-strength.png)\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n## `1.10` Consider the strength data for beams.\n\n### `a.` Construct a stem-and leaf display of the data. What appears to be a representative strength value? Do the observations appear to be highly concentrated about the representative value or rather spread out?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeam <- c(5.9, 7.2, 7.3, 6.3, 8.1, 6.8, 7.0, 7.6, 6.8, 6.5, 7.0, 6.3, 7.9, 9.0,\n         8.2, 8.7, 7.8, 9.7, 7.4, 7.7, 9.7, 7.8, 7.7, 11.6, 11.3, 11.8, 10.7)\nstem(beam)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n   5 | 9\n   6 | 33588\n   7 | 00234677889\n   8 | 127\n   9 | 077\n  10 | 7\n  11 | 368\n```\n:::\n:::\n\n\nA representative strength value would be 7.7, as more observations are concentrated around this value than any other.\n\n### `b.` Does the display appear to be reasonably symmetric about a representative value, or would you describe its shape in some other way?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nNo, I would argue that the data has a slight positive skewed to the right. I say this because the higher frequency values (in blues) seem to be to the left of the representative value (indicated by the red line), which is to the left of the mean (indicated by the orange line).\n\n### `c.` Do there appear to be any outlying strength values?\n\nYes there seems to be a small density of values outlying around 11.\n\n### `d.` What proportion of strength observations in this sample exceed 10 MPa?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"14.81 %\"\n```\n:::\n:::\n\n\nAn unlikely 14.81% of values exceed 10 MPa.\n\n## `1.12` The accompanying specific gravity values for various wood types used in construction appeared in the article \"Bolted Connection Design Values Based on European Yield Model\" (J. of Structural Engr., 1993: 2169-2186):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwood.g <- c(.31, .35, .36, .36, .37, .38, .40, .40, .40,\n            .41, .41, .42, .42, .42, .42, .42, .43, .44,\n            .45, .46, .46, .47, .48, .48, .48, .51, .54,\n            .54, .55, .58, .62, .66, .66, .67, .68, .75)\n```\n:::\n\n\n### Construct a stem-and-leaf display using repeated stems (see the previous exercise), and comment on any interesting features of the display.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  0 | 344444444444444444\n  0 | 555555555566677778\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  3 | 156678\n  4 | 0001122222345667888\n  5 | 14458\n  6 | 26678\n  7 | 5\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  3 | 1\n  3 | 56678\n  4 | 000112222234\n  4 | 5667888\n  5 | 144\n  5 | 58\n  6 | 2\n  6 | 6678\n  7 | \n  7 | 5\n```\n:::\n:::\n\n\nLooking at the three stem-and-leaf displays there are a few interesting features about the gravity for various wood types used in construction data that stands out. Dropping the last digit in the data, the first stem-and-leaf display shows us that there's an even number of values that are \\>0.5 and 0.5that appear most dense around 0.4. The second and third stem-and-leaf displays show us that these values are most dense about 0.42, with a small blip around 6.6 and obvious outlier for value 0.75.\n\n## `1.16` The article cited in Example 1.2 also gave the accompanying strengths observations for cylinders:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncylinders <- c(6.1, 5.8, 7.8, 7.1, 7.2, 9.2, 6.6, 8.3, 7.0, 8.3,\n           7.8, 8.1, 7.4, 8.5, 8.9, 9.8, 9.7, 14.1, 12.6, 11.2)\n```\n:::\n\n\n### `a.` Construct a comparative stem-and-leaf display (see the previous exercise) of the beam and cylinder data and then answer the questions in parts (b)-(d) of Exercise 10 for the observations on cylinders.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n   5 | 8\n   6 | 16\n   7 | 012488\n   8 | 13359\n   9 | 278\n  10 | \n  11 | 2\n  12 | 6\n  13 | \n  14 | 1\n```\n:::\n:::\n\n\n-   Does the display appear to be reasonably symmetric about a representative value, or would you describe its shape in some other way?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\ncylinders\n 5.8  6.1  6.6    7  7.1  7.2  7.4  8.1  8.5  8.9  9.2  9.7  9.8 11.2 12.6 14.1 \n   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1 \n 7.8  8.3 \n   2    2 \n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.575\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.2\n```\n:::\n:::\n\n\nThis data of cylinders also appears to have a slight positive skew, shown by mean (orange line) to the right of the median (red line) and mode (yellow line). However the mean is a lot closer to the median and mode in this than in the previous graph because there appear to bee less extreme observations.\n\n-   Do there appear to be any outlying strength values?\n\n14.1 appears to be an outlying strength value, as well as 11.2 and 12.6. Without these three values the mean and median are almost identical, shown below in cylinders.clean.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n [1] 6.1 5.8 7.8 7.1 7.2 9.2 6.6 8.3 7.0 8.3 7.8 8.1 7.4 8.5 8.9 9.8 9.7\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.858824\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.8\n```\n:::\n:::\n\n\n-   What proportion of strength observations in this sample exceed 10 MPa?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"15 %\"\n```\n:::\n:::\n\n\nAbout 15% of the data observations exceed 10 Mpa.\n\n### `b.` In what ways are the two sides of the display similar? Are there any obvious differences between the beam observations and the cylinder observations?\n\nBoth displays show relatively normal distributions with slight skews to the right. Similarly both the beam and cylinders have approximately 15% of the data outside the normal distribution. An obvious difference between the two is that the beam data was more skewed than the cylinder. A reason for this may be that the range of values for the beam is smaller than the range of values for cylinders, so the beam mean is more sensitive to outlying data.\n\n## `1.34` Exposure to microbial products, especially endotoxin, may have an impact on vulnerability to allergic diseases. The article \"Dust Sampling Methods for Endotoxin -- An Essential, But Underestimated Issue\" (Indoor Air, 2006: 20-27) considered various issues associated with determining endotoxin concentration. The following data on concentration (EU/mg) in settled dust for one sample of urban homes and another of farm homes was kindly supplied by the authors of the cited article.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurban <- c(6.0, 5.0, 11.0, 33.0, 4.0, 5.0, 80.0, 18.0, 35.0, 17.0, 23.0)\nfarm <- c(4.0, 14.0, 11.0, 9.0, 9.0, 8.0, 4.0, 20.0, 5.0, 8.9, 21.0, 9.2, 3.0, 2.0, 0.3 )\n```\n:::\n\n\n### `a.` Determine the sample mean for each sample. How do they compare?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(urban)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21.54545\n```\n:::\n\n```{.r .cell-code}\nmean(farm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.56\n```\n:::\n:::\n\n\nThe mean endotoxin concentration is greater in urban homes than farm homes.\n\n### `b.` Determine the sample median for each sample. How do they compare? Why is the median for the urban sample so different from the mean for that sample?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(urban)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17\n```\n:::\n\n```{.r .cell-code}\nmedian(farm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.9\n```\n:::\n:::\n\n\nThe median endotoxin concentration is greater in urban homes than farm homes.\n\nThe urban sample's median is so different from the mean, because the mean is more sensitive to outliers in the data (such as 80 EU/mg) than the median is.\n\n### `c.` Calculate the trimmed mean for each sample by deleting the smallest and largest observation. What are the corresponding trimming percentages? How do the values of these trimmed means compare to the corresponding means and medians?\n\nTo start I will sort the data to see what are the largest and smallest observations for both.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(urban)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  4  5  5  6 11 17 18 23 33 35 80\n```\n:::\n\n```{.r .cell-code}\nsort(farm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  0.3  2.0  3.0  4.0  4.0  5.0  8.0  8.9  9.0  9.0  9.2 11.0 14.0 20.0 21.0\n```\n:::\n:::\n\n\nFrom the sorted data I can see the lowest and highest values for urban are c(4,80), and for farm they are c(0.3,21). These values are removed from the urban.trim and farm.trim shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurban.trim <- c(6.0, 5.0, 11.0, 33.0, 5.0, 18.0, 35.0, 17.0, 23.0)\nfarm.trim <- c(4.0, 14.0, 11.0, 9.0, 9.0, 8.0, 4.0, 20.0, 5.0, 8.9, 9.2, 3.0, 2.0)\n```\n:::\n\n\nTo find the corresponding trimming percentages I subtracted the sum of the subtracted values from the sums of the urban and farm data sets respectively, and then divide each by the length of each data set respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(sum(urban)-84)/length(urban)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 13.90909\n```\n:::\n\n```{.r .cell-code}\n(sum(farm)-21.3)/length(farm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.14\n```\n:::\n:::\n\n\nThe two values removed from the urban dataset is about 14% of the data, slightly more then the 7.14% variation of the farm data set.\n\nNow to look at the trimmed means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(urban.trim)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17\n```\n:::\n\n```{.r .cell-code}\nmean(farm.trim)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.238462\n```\n:::\n:::\n\n\nThe trimmed mean of the urban data is closer to the median of the urban data, whereas the trimmed mean for the farm data is farther away from the mean and median of the untrimmed data. After this analysis it would seem that trimming the first data set may be appropriate, whereas trimming the second may lead to misleading data. Looking at the stem-and-leaf displays are helpful in visualizing distributions and outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstem(urban, scale = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  0 | 4556\n  1 | 178\n  2 | 3\n  3 | 35\n  4 | \n  5 | \n  6 | \n  7 | \n  8 | 0\n```\n:::\n\n```{.r .cell-code}\nstem(farm, scale = .5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  0 | 02344589999\n  1 | 14\n  2 | 01\n```\n:::\n:::\n\n\n## `1.48` Exercise 34 presented the following data on endotoxin concentration in settled dust both for a sample of urban homes and for a sample of farm homes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurban\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  6  5 11 33  4  5 80 18 35 17 23\n```\n:::\n\n```{.r .cell-code}\nfarm\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  4.0 14.0 11.0  9.0  9.0  8.0  4.0 20.0  5.0  8.9 21.0  9.2  3.0  2.0  0.3\n```\n:::\n:::\n\n\n### `a.` Determine the value of the sample standard deviation for each sample, interpret these values, and then contrast variability in the two samples.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(urban)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 22.29961\n```\n:::\n\n```{.r .cell-code}\nsd(farm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.087669\n```\n:::\n:::\n\n\nAnother way we could find the standard deviation given the hint and the following equation given in class :\n\n\\[s\\^2=\\frac{1}{n-1}\\sum\\_{i=1}\\^{n}(x_i - x)\\^2\\] \\[=\\frac{1}{n-1}\\[\\sum\\_{i=1}^{n}x_i^2 - \\frac{(\\sum_{i=1}^{n}x_i)^2}{n}\\]\\]\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# hint\nsigma_x_i.u <- 237.0\nsigma_x_i.f <- 128.4\nsigma_x_i_2.u <- 10079\nsigma_x_i_2.f <- 1617.94\nn.u <- length(urban)\nn.f <- length(farm)\nconstant.u <- 1/(n.u-1)\nconstant.f <- 1/(n.f-1)\nsv.u <- constant.u*(sigma_x_i_2.u - (sigma_x_i.u)^2/n.u)\nsv.f <- constant.f*(sigma_x_i_2.f - (sigma_x_i.f)^2/n.f)\nsqrt(sv.u)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 22.29961\n```\n:::\n\n```{.r .cell-code}\nsqrt(sv.f)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.087669\n```\n:::\n:::\n\n\n### `b.` Compute the fourth spread for each sample and compare. Do the fourth spreads convey the same message about variability that the standard deviations do? Explain.\n\nThe quickest way to do this in r is with quantile().\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(urban)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  0%  25%  50%  75% 100% \n 4.0  5.5 17.0 28.0 80.0 \n```\n:::\n\n```{.r .cell-code}\nquantile(farm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  0%  25%  50%  75% 100% \n 0.3  4.0  8.9 10.1 21.0 \n```\n:::\n:::\n\n\nExplanation : coming soon\n\nAnother way to find the forth spread is by first computing the upper fourth and lower fourth . To do that I first sorted the data, and then split it in half. Notice that because n for both data sets is odd, I figure out the middle value that is included in both, before I create the new data sets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sort \nsorted.u <- sort(urban)\nsorted.f <- sort(farm)\nsorted.u\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  4  5  5  6 11 17 18 23 33 35 80\n```\n:::\n\n```{.r .cell-code}\nsorted.f\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  0.3  2.0  3.0  4.0  4.0  5.0  8.0  8.9  9.0  9.0  9.2 11.0 14.0 20.0 21.0\n```\n:::\n\n```{.r .cell-code}\n# find included value \ninclude.u <- as.integer(n.u/2)+1\ninclude.f <- as.integer(n.f/2)+1\nsorted.u[include.u]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17\n```\n:::\n\n```{.r .cell-code}\nsorted.f[include.f]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.9\n```\n:::\n\n```{.r .cell-code}\n# upper and lower forth \nurban.lower <- c(4,  5,  5,  6, 11, 17)\nurban.upper <- c(17, 18, 23, 33, 35, 80)\nfarm.lower <- c(0.3,  2.0,  3.0,  4.0,  4.0,  5.0,  8.0,  8.9)\nfarm.upper <- c(8.9,  9.0,  9.0,  9.2, 11.0, 14.0, 20.0, 21.0)\n```\n:::\n\n\nNow that the data is sorted, the middle values of 17 and 8.9 have been found, and the data has been split into two chunks I can compute the minimum,lower forth median, median, upper forth median, and the largest value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(urban)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n\n```{.r .cell-code}\nmedian(urban.lower)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.5\n```\n:::\n\n```{.r .cell-code}\nmedian(urban)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17\n```\n:::\n\n```{.r .cell-code}\nmedian(urban.upper)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 28\n```\n:::\n\n```{.r .cell-code}\nmax(urban)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\nmin(farm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3\n```\n:::\n\n```{.r .cell-code}\nmedian(farm.lower)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n\n```{.r .cell-code}\nmedian(farm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.9\n```\n:::\n\n```{.r .cell-code}\nmedian(farm.upper)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.1\n```\n:::\n\n```{.r .cell-code}\nmax(farm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21\n```\n:::\n:::\n\n\n-   The authors of the cited article also provided endotoxin concentrations in dust bag dust:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurban.bag <- c(34.0, 49.0, 13.0, 33.0, 24.0, 24.0, 35.0, 104.0, 34.0, 40.0, 38.0, 1.0)\nfarm.bag <- c(2.0, 64.0, 6.0, 17.0, 35.0, 11.0, 17.0, 13.0, 5.0, 27.0, 23.0,\n              28.0, 10.0, 13.0, 0.2)\nquantile(urban.bag)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   0%   25%   50%   75%  100% \n  1.0  24.0  34.0  38.5 104.0 \n```\n:::\n\n```{.r .cell-code}\nquantile(farm.bag)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  0%  25%  50%  75% 100% \n 0.2  8.0 13.0 25.0 64.0 \n```\n:::\n:::\n\n\nConstruct a comparative boxplot (as did the cited paper) and compare and contrast the four samples.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1,2))\nboxplot(urban)\nboxplot(urban.bag)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1,2))\nboxplot(farm)\nboxplot(farm.bag)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-28-2.png){width=672}\n:::\n:::\n\n\n## `1.51` The article \"A Thin-Film Oxygen Uptake Test for the Evaluation of Automotive Crankcase Lubricants\" (Lubric. Engr., 1984: 75-83) reported the following data on oxidation-induction time (min) for various commercial oils:\n\n\n::: {.cell}\n\n```{.r .cell-code}\noxi.induct.time.min <- c(87, 103, 130, 160, 180, 195, 132, 145, 211, 105, 145,\n                         153, 152, 138, 87, 99, 93, 119, 129)\n```\n:::\n\n\n### `a.` Calculate the sample variance and the standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noxi.var <- var(oxi.induct.time.min)\noxi.sd <- sd(oxi.induct.time.min)\noxi.var\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1264.766\n```\n:::\n\n```{.r .cell-code}\noxi.sd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 35.56355\n```\n:::\n:::\n\n\n### `b.` If the observations were re-expressed in hours, what would be the resulting values of the sample variance and sample standard deviation? Answer without actually performing the re-expression.\n\nThe standard deviation has the same units as the data values (minutes) so in hours the standard deviation would be 35.56/60 (or a little over half an hour) whereas the variance is the standard deviation squared, so the values would be converted 1264.766/60\\^2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noxi.var/60^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3513239\n```\n:::\n\n```{.r .cell-code}\noxi.sd/60\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5927258\n```\n:::\n\n```{.r .cell-code}\n# verification \noxi.induct.time.hour <- oxi.induct.time.min/60\nvar(oxi.induct.time.hour)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3513239\n```\n:::\n\n```{.r .cell-code}\nsd(oxi.induct.time.hour) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5927258\n```\n:::\n:::\n\n\n## `1.60` Observations on burst strength (lb/in2) were obtained both for test nozzle welds (\"Proper Procedures Are the Key to Welding Radioactive Waste Canisters,\" Welding J., Auud. 1997: 61-67)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTest <-c(7200, 6100, 7300, 7300, 8000, 7400,\n         7300, 7300, 8000, 6700, 8300)         \nCannister <- c(5250, 5625, 5900, 5900, 5700, 6050,\n               5800, 6000, 5875, 6100, 5850, 6600)\n```\n:::\n\n\n### `a.` Construct a comparative boxplot and comment on interesting features (the cited article did not include such a picture, but the authors commented that they had looked at one).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1,2))\nboxplot(Test, ylim = c(5000, 8500), main = \"Test\")\nboxplot(Cannister, ylim = c(5000, 8500), main = \"Cannister\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(Test)-mean(Cannister)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1467.045\n```\n:::\n\n```{.r .cell-code}\nmean(Test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7354.545\n```\n:::\n\n```{.r .cell-code}\nmean(Cannister)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5887.5\n```\n:::\n\n```{.r .cell-code}\nsd(Test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 613.7811\n```\n:::\n\n```{.r .cell-code}\nsd(Cannister)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 317.9301\n```\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}