project:
  type: website

website:
  title: "Randi Bolt"
  favicon: img/rbolt.png
  google-analytics: "G-GPSGHZ166H"
  page-footer: 
    left: "Made with [Quarto](https://quarto.org/) and deployed with [Netlify](https://www.netlify.com/)."
    center: 'Randi Bolt 2023'
  navbar:
    right:
      - href: blog.qmd
        text: Blog
        aria-label: Blog
      - href: projects.qmd
        text: Projects
        aria-label: Projects
      - href: resume.qmd
        text: Resume
        aria-label: Resume
      - icon: github
        href: https://github.com/rbolt13
        aria-label: GitHub
      - icon: mastodon
        href: https://pnw.zone/@rbolt
        aria-label: Mastodon
      - icon: linkedin
        href: https://www.linkedin.com/in/randi-bolt/
        aria-label: Linkedin
format:
  html:
    theme: 
      light: [scss/light-theme.scss]
      dark: [scss/dark-theme.scss]
    template-partials:
      - metadata.html

comments: 
  giscus:
    repo: rbolt13/rbolt22
