project:
  type: website

website:
  title: "Randi Bolt"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rbolt13
      - icon: linkedin
        href: https://www.linkedin.com/in/randi-bolt/
      - icon: instagram
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: visual

