project:
  type: website

website:
  title: "Randi Bolt"
  navbar:
    right:
      - 01_datsci.qmd
      - 02_math.qmd
      - 03_stat.qmd
      - icon: github
        href: https://github.com/rbolt13
      - icon: linkedin
        href: https://www.linkedin.com/in/randi-bolt/
      - icon: instagram
        href: https://www.instagram.com/rbolt13/
format:
  html:
    theme: journal
    backgroundcolor: pink
    css: styles.css

editor: visual

comments: 
  giscus:
    repo: rbolt13/rbolt22
