<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2021-12-20">

<title>Randi Bolt - Transformations and Weighting to Correct Model Inadequacies</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../00_img/pink-bolt.jpeg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Randi Bolt</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">about</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html">blog</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html">resume</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rbolt13"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://pnw.zone/@rbolt"><i class="bi bi-mastodon" role="img" aria-label="Mastodon">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://open.spotify.com/user/innluxglueuzbltzfxgbsc2dz?si=b2fd3674e2694dd3"><i class="bi bi-spotify" role="img" aria-label="Spotify">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/randi-bolt/"><i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Transformations and Weighting to Correct Model Inadequacies</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">Linear Regression</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 20, 2021</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#set-up" id="toc-set-up" class="nav-link active" data-scroll-target="#set-up"><code>1.</code> Set Up</a></li>
  <li><a href="#example-5.1-the-electric-utility-data" id="toc-example-5.1-the-electric-utility-data" class="nav-link" data-scroll-target="#example-5.1-the-electric-utility-data"><code>2.</code> Example 5.1: The Electric Utility Data</a></li>
  <li><a href="#example-5.2-the-windmill-data" id="toc-example-5.2-the-windmill-data" class="nav-link" data-scroll-target="#example-5.2-the-windmill-data"><code>3.</code> Example 5.2: The Windmill Data</a></li>
  <li><a href="#example-5.3-the-electic-utility-data" id="toc-example-5.3-the-electic-utility-data" class="nav-link" data-scroll-target="#example-5.3-the-electic-utility-data"><code>4. Example 5.3: The Electic Utility Data</code></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>This post covers examples from Chapter 5 of <a href="https://www.amazon.com/Introduction-Regression-Analysis-Douglas-Montgomery/dp/0470542810">Introduction to Linear Regression Analysis</a>.</p>
<p><img src="slr_meme.jpeg" class="img-fluid"></p>
<section id="set-up" class="level1">
<h1><code>1.</code> Set Up</h1>
<p>For this analysis I will be using four packages:</p>
<ul>
<li><p>magrittr: for piping (%&gt;%)</p></li>
<li><p>dplyr: to arrange the data</p></li>
<li><p>MASS: to use the boxcox function</p></li>
<li><p>latex2exp: to put latex on graphs</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(latex2exp) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr) </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="example-5.1-the-electric-utility-data" class="level1">
<h1><code>2.</code> Example 5.1: The Electric Utility Data</h1>
<p>An electric utility company is interested in developing a model relating peak-hour demand <span class="math inline">\((y)\)</span> to total energy usage during the month <span class="math inline">\((x)\)</span>.</p>
<p>To start lets look at the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>ex51 <span class="ot">&lt;-</span> utils<span class="sc">::</span><span class="fu">read.csv</span>(<span class="st">"data/ex5-1.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>ex51</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    X Customer x_.kWh. y_.kW.
1   1        1     679   0.79
2   2        2     292   0.44
3   3        3    1012   0.56
4   4        4     493   0.79
5   5        5     582   2.70
6   6        6    1156   3.64
7   7        7     997   4.73
8   8        8    2189   9.50
9   9        9    1097   5.34
10 10       10    2078   6.85
11 11       11    1818   5.84
12 12       12    1700   5.21
13 13       13     747   3.25
14 14       14    2030   4.43
15 15       15    1643   3.16
16 16       16     414   0.50
17 17       17     354   0.17
18 18       18    1276   1.88
19 19       19     745   0.77
20 20       20     435   1.39
21 21       21     540   0.56
22 22       22     874   1.56
23 23       23    1543   5.28
24 24       24    1029   0.64
25 25       25     710   4.00
26 26       26    1434   0.31
27 27       27     837   4.20
28 28       28    1748   4.88
29 29       29    1381   3.48
30 30       30    1428   7.58
31 31       31    1255   2.63
32 32       32    1777   4.99
33 33       33     370   0.59
34 34       34    2316   8.19
35 35       35    1130   4.79
36 36       36     463   0.51
37 37       37     770   1.74
38 38       38     724   4.10
39 39       39     808   3.94
40 40       40     790   0.96
41 41       41     783   3.29
42 42       42     406   0.44
43 43       43    1242   3.24
44 44       44     658   2.14
45 45       45    1746   5.71
46 46       46     468   0.64
47 47       47    1114   1.90
48 48       48     413   0.51
49 49       49    1787   8.33
50 50       50    3560  14.94
51 51       51    1495   5.11
52 52       52    2221   3.85
53 53       53    1526   3.93</code></pre>
</div>
</div>
<p>Right away we can see that for each customer there is a value <code>x_.kWH</code> for Kilowatt hour which corresponds to energy usage during the month, and <code>y_.kW</code> for kilowatt which would then be peak-hour demand. The plot of this is shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">plot</span>(ex51<span class="sc">$</span>x_.kWh., </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>           ex51<span class="sc">$</span>y_.kW.,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab =</span> <span class="st">"Usage"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab =</span> <span class="st">"Demand"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Scatter diagram of the energy demand (kW) versus energy usage (kWh)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>As a starting point a simple linear regression model is assumed. Lets look at the summary to get an equation for the <a href="https://mathworld.wolfram.com/LeastSquaresFitting.html#:~:text=A%20mathematical%20procedure%20for%20finding,the%20points%20from%20the%20curve.">least-squares fit</a>, and analyze variability.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lm51 <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(ex51<span class="sc">$</span>y_.kW. <span class="sc">~</span> ex51<span class="sc">$</span>x_.kWh., <span class="at">data =</span> ex51)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm51)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = ex51$y_.kW. ~ ex51$x_.kWh., data = ex51)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.1399 -0.8275 -0.1934  1.2376  3.1522 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.8313037  0.4416121  -1.882   0.0655 .  
ex51$x_.kWh.  0.0036828  0.0003339  11.030 4.11e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.577 on 51 degrees of freedom
Multiple R-squared:  0.7046,    Adjusted R-squared:  0.6988 
F-statistic: 121.7 on 1 and 51 DF,  p-value: 4.106e-15</code></pre>
</div>
</div>
<p>From our summary our we can extrapolate our least-squares fit is: <span class="math inline">\(\hat y=-0.83130+0.00368x\)</span></p>
<p>For this model <span class="math inline">\(R^2=0.7046\)</span>; that is about 70% of the variability in demand is accounted for by the straight-line fit to energy usage. The summary statistics do not reveal any obvious problems with this model.</p>
<p>Below this model is plotted with a red line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">plot</span>(ex51<span class="sc">$</span>x_.kWh.,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>           ex51<span class="sc">$</span>y_.kW.,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab =</span> <span class="st">"Usage"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab =</span> <span class="st">"Demand"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>graphics<span class="sc">::</span><span class="fu">abline</span>(lm51, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Scatter diagram of the energy demand (kW) versus energy usage (kWh) with Simple Linear Model</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>From visual inspection we can see the points on the far left side of the graph are much closer to the best fit line than those in the middle and right side of the graph. We might want to apply a transformation to this model, so lets look at the <a href="https://en.wikipedia.org/wiki/Studentized_residual#:~:text=In%20statistics%2C%20a%20studentized%20residual,in%20the%20detection%20of%20outliers.">Studentized Residual</a> also known as r student.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">plot</span>(stats<span class="sc">::</span><span class="fu">fitted</span>(lm51),</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>           stats<span class="sc">::</span><span class="fu">rstudent</span>(lm51),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab=</span>latex2exp<span class="sc">::</span><span class="fu">TeX</span>(r<span class="st">'($t_i$)'</span>),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab=</span>latex2exp<span class="sc">::</span><span class="fu">TeX</span>(r<span class="st">'($\hat{y}_i$)'</span>),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">pch =</span> <span class="dv">16</span>);graphics<span class="sc">::</span><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>,<span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Plot of R-Student vs.&nbsp;fitted values</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>From this graph we can see that the residuals form an outward-opening funnel, indicating that the error variance is increasing as energy consumption increases. A transformation may be helpful in correcting this model inadequacy. To select the form of the transformation, note that the response variable y may be viewed as a “count” of the number of kilowatts used by a customer during a particular hour. The simplest probabilistic model for count data is the <a href="https://en.wikipedia.org/wiki/Poisson_distribution">Poisson distribution</a>. This suggests regressing <span class="math inline">\(y^*=\sqrt{y}\)</span> on x as a variance-stabilizing transformation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>ex51<span class="sc">$</span>ystar <span class="ot">&lt;-</span> base<span class="sc">::</span><span class="fu">sqrt</span>(ex51<span class="sc">$</span>y_.kW.)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>lm51T <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(ex51<span class="sc">$</span>ystar <span class="sc">~</span> ex51<span class="sc">$</span>x_.kWh., <span class="at">data =</span> ex51)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">summary</span>(lm51T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = ex51$ystar ~ ex51$x_.kWh., data = ex51)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.39185 -0.30576 -0.03875  0.25378  0.81027 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.822e-01  1.299e-01   4.481 4.22e-05 ***
ex51$x_.kWh. 9.529e-04  9.824e-05   9.699 3.61e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.464 on 51 degrees of freedom
Multiple R-squared:  0.6485,    Adjusted R-squared:  0.6416 
F-statistic: 94.08 on 1 and 51 DF,  p-value: 3.614e-13</code></pre>
</div>
</div>
<p>The resulting least-squares fit is: <span class="math inline">\(\hat y^*=0.5822+0.0009529x\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">plot</span>(stats<span class="sc">::</span><span class="fu">fitted</span>(lm51T),</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>           stats<span class="sc">::</span><span class="fu">rstudent</span>(lm51T),</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab=</span>latex2exp<span class="sc">::</span><span class="fu">TeX</span>(r<span class="st">'($t_i$)'</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab=</span>latex2exp<span class="sc">::</span><span class="fu">TeX</span>(r<span class="st">'($\hat{y}^*_i$)'</span>),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">pch =</span> <span class="dv">16</span>);graphics<span class="sc">::</span><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>,<span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The impression from examining this plot is that the variance is stable; consequently, we conclude that the transformed model is adequate.</p>
<p>Note that there is one suspiciously large residual (customer 26) and one customer whose energy usage is somewhat large (customer 50). The effect of these two points on the fit should be studied further before the model is released for use.</p>
</section>
<section id="example-5.2-the-windmill-data" class="level1">
<h1><code>3.</code> Example 5.2: The Windmill Data</h1>
<p>A research engineer is investigating the use of a windmill to generate electricity. He has collected data on the DC Output from his windmill and the corresponding wind velocity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ex52 <span class="ot">&lt;-</span> utils<span class="sc">::</span><span class="fu">read.csv</span>(<span class="st">"data/ex5-2.csv"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>utils<span class="sc">::</span><span class="fu">head</span>(ex52)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X ObservationNumber_i WindVelocity_xi_mph DCOutput_yi
1 1                   1                 5.0       1.582
2 2                   2                 6.0       1.822
3 3                   3                 3.4       1.057
4 4                   4                 2.7       0.500
5 5                   5                10.0       2.236
6 6                   6                 9.7       2.386</code></pre>
</div>
</div>
<p>The data is plotted below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">plot</span>(ex52<span class="sc">$</span>WindVelocity_xi_mph,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>           ex52<span class="sc">$</span>DCOutput_yi,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab =</span> <span class="st">"Wind Velocity, X"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab =</span> <span class="st">"DC Output, Y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Inspection of the scatter diagram indicates that the relationship between DC output <span class="math inline">\((y)\)</span> and wind velocity <span class="math inline">\((x)\)</span> may be nonlinear. However, we initially fit a straight-line model to the data, and look at the summary statistics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>lm52 <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(ex52<span class="sc">$</span>DCOutput_yi <span class="sc">~</span> ex52<span class="sc">$</span>WindVelocity_xi_mph, <span class="at">data =</span> ex52)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">summary</span>(lm52)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = ex52$DCOutput_yi ~ ex52$WindVelocity_xi_mph, 
    data = ex52)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.59869 -0.14099  0.06059  0.17262  0.32184 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               0.13088    0.12599   1.039     0.31    
ex52$WindVelocity_xi_mph  0.24115    0.01905  12.659 7.55e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2361 on 23 degrees of freedom
Multiple R-squared:  0.8745,    Adjusted R-squared:  0.869 
F-statistic: 160.3 on 1 and 23 DF,  p-value: 7.546e-12</code></pre>
</div>
</div>
<p>The summary statistics for this model are <span class="math inline">\(R^2=0.8745\)</span>, and <span class="math inline">\(F_0=160.26\)</span> (the P-value is &lt;0.0001), and he regression model is: <span class="math inline">\(\hat y=0.1309+0.2411x\)</span>, shown in red below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">plot</span>(ex52<span class="sc">$</span>WindVelocity_xi_mph,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>           ex52<span class="sc">$</span>DCOutput_yi,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab =</span> <span class="st">"Wind Velocity, x"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab =</span> <span class="st">"DC Output, Y"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>graphics<span class="sc">::</span><span class="fu">abline</span>(lm52, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Below we can extract the fitted and residual values from our linear model, and then arrange them in order of increasing wind speed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ex52<span class="sc">$</span>fitted <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">fitted</span>(lm52)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>ex52<span class="sc">$</span>resid <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">resid</span>(lm52)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>ex52 <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">arrange</span>(<span class="sc">-</span>dplyr<span class="sc">::</span><span class="fu">desc</span>(ex52<span class="sc">$</span>WindVelocity_xi_mph)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    X ObservationNumber_i WindVelocity_xi_mph DCOutput_yi    fitted       resid
1  25                  25                2.45       0.123 0.7216899 -0.59868986
2   4                   4                2.70       0.500 0.7819771 -0.28197708
3  11                  11                2.90       0.653 0.8302069 -0.17720685
4   8                   8                3.05       0.558 0.8663792 -0.30837918
5   3                   3                3.40       1.057 0.9507813  0.10621871
6  16                  16                3.60       1.137 0.9990111  0.13798894
7  24                  24                3.95       1.144 1.0834132  0.06058683
8  23                  23                4.10       1.194 1.1195855  0.07441450
9  13                  13                4.60       1.562 1.2401599  0.32184007
10  1                   1                5.00       1.582 1.3366195  0.24538052
11 20                  20                5.45       1.501 1.4451365  0.05586353
12 14                  14                5.80       1.737 1.5295386  0.20746142
13  2                   2                6.00       1.822 1.5777683  0.24423165
14 10                  10                6.20       1.866 1.6259981  0.24000188
15 12                  12                6.35       1.930 1.6621705  0.26782955
16 19                  19                7.00       1.800 1.8189172 -0.01891722
17 15                  15                7.40       2.088 1.9153768  0.17262323
18 17                  17                7.85       2.179 2.0238938  0.15510624
19  9                   9                8.15       2.166 2.0962384  0.06976158
20 18                  18                8.80       2.112 2.2529852 -0.14098518
21 21                  21                9.10       2.303 2.3253298 -0.02232985
22  7                   7                9.55       2.294 2.4338468 -0.13984684
23  6                   6                9.70       2.386 2.4700192 -0.08401917
24  5                   5               10.00       2.236 2.5423638 -0.30636383
25 22                  22               10.20       2.310 2.5905936 -0.28059360</code></pre>
</div>
</div>
<p>The residuals show a distinct pattern, that is, they move systematically from negative to positive and back to negative again as wind speed increases.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">plot</span>(stats<span class="sc">::</span><span class="fu">fitted</span>(lm52),</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>           stats<span class="sc">::</span><span class="fu">resid</span>(lm52),</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab=</span><span class="fu">TeX</span>(r<span class="st">'($e_i$)'</span>),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab=</span><span class="fu">TeX</span>(r<span class="st">'($\hat{y}_i$)'</span>),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">pch =</span> <span class="dv">16</span>);graphics<span class="sc">::</span><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>,<span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This residual plot indicates model inadequacy and implies that the linear relationship has not captured all of the information in the wind speed variable. Note that the curvature was apparent in the earlier scatter diagram, but is greatly amplified in the residual plot</p>
<p>Clearly some other model form must be considered. We might initially consider using a quadratic model such as: <span class="math inline">\(y=\beta_0+\beta_1x+\beta_2x^2+\epsilon\)</span> to account for the curvature. However since the quadratic model will eventually bend downward as wind speed increases, it would not be appropriate for these data. A more reasonable model for windmill data that incorporates an upper asymptote would be: <span class="math inline">\(y=\beta_0+\beta_1(\frac{1}{x})+\epsilon\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>ex52<span class="sc">$</span>xstar <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>ex52<span class="sc">$</span>WindVelocity_xi_mph</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>lm52T <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(ex52<span class="sc">$</span>DCOutput_yi <span class="sc">~</span> ex52<span class="sc">$</span>xstar, <span class="at">data =</span> ex52)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">summary</span>(lm52T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = ex52$DCOutput_yi ~ ex52$xstar, data = ex52)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.20547 -0.04940  0.01100  0.08352  0.12204 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.9789     0.0449   66.34   &lt;2e-16 ***
ex52$xstar   -6.9345     0.2064  -33.59   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.09417 on 23 degrees of freedom
Multiple R-squared:   0.98, Adjusted R-squared:  0.9792 
F-statistic:  1128 on 1 and 23 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The fitted regression model is <span class="math inline">\(\hat y=2.9789-6.9345x'\)</span></p>
<p>The summary statistics for this model are <span class="math inline">\(R^2=0.98\)</span>, and <span class="math inline">\(F_0=1128\)</span> (the p value is &lt;0.0001).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">plot</span>(stats<span class="sc">::</span><span class="fu">fitted</span>(lm52T),</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>           stats<span class="sc">::</span><span class="fu">rstudent</span>(lm52T),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab=</span><span class="fu">TeX</span>(r<span class="st">'($t_i$)'</span>),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab=</span><span class="fu">TeX</span>(r<span class="st">'($\hat{y}_i$)'</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">pch =</span> <span class="dv">16</span>);graphics<span class="sc">::</span><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>,<span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This plot does not reveal any serious problems.</p>
</section>
<section id="example-5.3-the-electic-utility-data" class="level1">
<h1><code>4. Example 5.3: The Electic Utility Data</code></h1>
<p>We use the <a href="https://www.statisticshowto.com/probability-and-statistics/normal-distributions/box-cox-transformation/">Box-Cox</a> procedure to select a variance-stabilizing transformation. The values of <span class="math inline">\(SS_{Res}(\lambda)\)</span> for various values are shown in the table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>boxcoxResult <span class="ot">=</span> MASS<span class="sc">::</span><span class="fu">boxcox</span>(ex51<span class="sc">$</span>y_.kW. <span class="sc">~</span> ex51<span class="sc">$</span>x_.kWh., <span class="at">data =</span> ex51, <span class="at">lambda =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="dv">2</span>,<span class="fl">0.125</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Box-Cox graph shows most of the data is below the 95% confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> boxcoxResult<span class="sc">$</span>x[<span class="fu">which.max</span>(boxcoxResult<span class="sc">$</span>y)]</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>lambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5454545</code></pre>
</div>
</div>
<p>Where <span class="math inline">\(\lambda\approx\)</span> 0.5454545 could be used as an appropriate exponent to use to transform the data into a “normal shape.”</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="rbolt13/rbolt22" data-repo-id="R_kgDOIJG8zw" data-category="General" data-category-id="DIC_kwDOIJG8z84CSd2f" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>