{
  "hash": "52a00f1e42eec089ec5d2852069b08ab",
  "result": {
    "markdown": "---\ntitle: \"Transformations and Weighting to Correct Model Inadequacies\"\ndate: \"2021-12-20\"\ncategories: [R, Linear Regression]\ntoc: true\n---\n\n\nThis post covers examples from Chapter 5 of [Introduction to Linear Regression Analysis](https://www.amazon.com/Introduction-Regression-Analysis-Douglas-Montgomery/dp/0470542810). \n\n![](../../00_img/slr_meme.jpeg)\n\n# `1. Set Up`\n\nFor this analysis I will be using four packages: \n\n* magrittr: for piping (%>%)\n\n* dplyr: to arrange the data\n\n* MASS: to use the boxcox function\n\n* latex2exp: to put latex on graphs \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(latex2exp) \nlibrary(magrittr) \nlibrary(dplyr) \nlibrary(MASS) \n```\n:::\n\n\n# `2. Example 5.1: The Electric Utility Data`\n\nAn electric utility company is interested in developing a model relating peak-hour demand $(y)$ to total energy usage during the month $(x)$. \n\nTo start lets look at the data. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nex51 <- utils::read.csv(\"../../00_data/ex5-1.csv\")\nex51\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    X Customer x_.kWh. y_.kW.\n1   1        1     679   0.79\n2   2        2     292   0.44\n3   3        3    1012   0.56\n4   4        4     493   0.79\n5   5        5     582   2.70\n6   6        6    1156   3.64\n7   7        7     997   4.73\n8   8        8    2189   9.50\n9   9        9    1097   5.34\n10 10       10    2078   6.85\n11 11       11    1818   5.84\n12 12       12    1700   5.21\n13 13       13     747   3.25\n14 14       14    2030   4.43\n15 15       15    1643   3.16\n16 16       16     414   0.50\n17 17       17     354   0.17\n18 18       18    1276   1.88\n19 19       19     745   0.77\n20 20       20     435   1.39\n21 21       21     540   0.56\n22 22       22     874   1.56\n23 23       23    1543   5.28\n24 24       24    1029   0.64\n25 25       25     710   4.00\n26 26       26    1434   0.31\n27 27       27     837   4.20\n28 28       28    1748   4.88\n29 29       29    1381   3.48\n30 30       30    1428   7.58\n31 31       31    1255   2.63\n32 32       32    1777   4.99\n33 33       33     370   0.59\n34 34       34    2316   8.19\n35 35       35    1130   4.79\n36 36       36     463   0.51\n37 37       37     770   1.74\n38 38       38     724   4.10\n39 39       39     808   3.94\n40 40       40     790   0.96\n41 41       41     783   3.29\n42 42       42     406   0.44\n43 43       43    1242   3.24\n44 44       44     658   2.14\n45 45       45    1746   5.71\n46 46       46     468   0.64\n47 47       47    1114   1.90\n48 48       48     413   0.51\n49 49       49    1787   8.33\n50 50       50    3560  14.94\n51 51       51    1495   5.11\n52 52       52    2221   3.85\n53 53       53    1526   3.93\n```\n:::\n:::\n\n\nRight away we can see that for each customer there is a value `x_.kWH` for Kilowatt hour which corresponds to energy usage during the month, and `y_.kW` for kilowatt which would then be peak-hour demand. The plot of this is shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::plot(ex51$x_.kWh., \n           ex51$y_.kW.,\n           xlab = \"Usage\",\n           ylab = \"Demand\")\n```\n\n::: {.cell-output-display}\n![Scatter diagram of the energy demand (kW) versus energy usage (kWh)](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nAs a starting point a simple linear regression model is assumed. Lets look at the summary to get an equation for the [least-squares fit](https://mathworld.wolfram.com/LeastSquaresFitting.html#:~:text=A%20mathematical%20procedure%20for%20finding,the%20points%20from%20the%20curve.), and analyze variability. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm51 <- stats::lm(ex51$y_.kW. ~ ex51$x_.kWh., data = ex51)\nsummary(lm51)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nstats::lm(formula = ex51$y_.kW. ~ ex51$x_.kWh., data = ex51)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.1399 -0.8275 -0.1934  1.2376  3.1522 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -0.8313037  0.4416121  -1.882   0.0655 .  \nex51$x_.kWh.  0.0036828  0.0003339  11.030 4.11e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.577 on 51 degrees of freedom\nMultiple R-squared:  0.7046,\tAdjusted R-squared:  0.6988 \nF-statistic: 121.7 on 1 and 51 DF,  p-value: 4.106e-15\n```\n:::\n:::\n\n\nFrom our summary our we can extrapolate our least-squares fit is: $\\hat y=-0.83130+0.00368x$ \n\nFor this model $R^2=0.7046$; that is about 70% of the variability in demand is accounted for by the straight-line fit to energy usage. The summary statistics do not reveal any obvious problems with this model. \n\nBelow this model is plotted with a red line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::plot(ex51$x_.kWh.,\n           ex51$y_.kW.,\n           xlab = \"Usage\",\n           ylab = \"Demand\")\ngraphics::abline(lm51, col = \"red\")\n```\n\n::: {.cell-output-display}\n![Scatter diagram of the energy demand (kW) versus energy usage (kWh) with Simple Linear Model](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nFrom visual inspection we can see the points on the far left side of the graph are much closer to the best fit line than those in the middle and right side of the graph. We might want to apply a transformation to this model, so lets look at the [Studentized Residual](https://en.wikipedia.org/wiki/Studentized_residual#:~:text=In%20statistics%2C%20a%20studentized%20residual,in%20the%20detection%20of%20outliers.) also known as r student.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::plot(stats::fitted(lm51),\n           stats::rstudent(lm51),\n           ylab=latex2exp::TeX(r'($t_i$)'),\n           xlab=latex2exp::TeX(r'($\\hat{y}_i$)'),\n           pch = 16);graphics::abline(0, 0,lty = 2)\n```\n\n::: {.cell-output-display}\n![Plot of R-Student vs. fitted values](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nFrom this graph we can see that the residuals form an outward-opening funnel, indicating that the error variance is increasing as energy consumption increases. A transformation may be helpful in correcting this model inadequacy. To select the form of the transformation, note that the response variable y may be viewed as a \"count\" of the number of kilowatts used by a customer during a particular hour. The simplest probabilistic model for count data is the [Poisson distribution](https://en.wikipedia.org/wiki/Poisson_distribution). This suggests regressing $y^*=\\sqrt{y}$ on x as a variance-stabilizing transformation. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nex51$ystar <- base::sqrt(ex51$y_.kW.)\nlm51T <- stats::lm(ex51$ystar ~ ex51$x_.kWh., data = ex51)\nbase::summary(lm51T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nstats::lm(formula = ex51$ystar ~ ex51$x_.kWh., data = ex51)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.39185 -0.30576 -0.03875  0.25378  0.81027 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  5.822e-01  1.299e-01   4.481 4.22e-05 ***\nex51$x_.kWh. 9.529e-04  9.824e-05   9.699 3.61e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.464 on 51 degrees of freedom\nMultiple R-squared:  0.6485,\tAdjusted R-squared:  0.6416 \nF-statistic: 94.08 on 1 and 51 DF,  p-value: 3.614e-13\n```\n:::\n:::\n\n\nThe resulting least-squares fit is: $\\hat y^*=0.5822+0.0009529x$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::plot(stats::fitted(lm51T),\n           stats::rstudent(lm51T),\n           ylab=latex2exp::TeX(r'($t_i$)'),\n           xlab=latex2exp::TeX(r'($\\hat{y}^*_i$)'),\n           pch = 16);graphics::abline(0, 0,lty = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe impression from examining this plot is that the variance is stable; consequently, we conclude that the transformed model is adequate. \n\nNote that there is one suspiciously large residual (customer 26) and one customer whose energy usage is somewhat large (customer 50). The effect of these two points on the fit should be studied further before the model is released for use. \n\n# `3. Example 5.2: The Windmill Data`\n\nA research engineer is investigating the use of a windmill to generate electricity. He has collected data on the DC Output from his windmill and the corresponding wind velocity. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nex52 <- utils::read.csv(\"../../00_data/ex5-2.csv\")\nutils::head(ex52)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  X ObservationNumber_i WindVelocity_xi_mph DCOutput_yi\n1 1                   1                 5.0       1.582\n2 2                   2                 6.0       1.822\n3 3                   3                 3.4       1.057\n4 4                   4                 2.7       0.500\n5 5                   5                10.0       2.236\n6 6                   6                 9.7       2.386\n```\n:::\n:::\n\n\nThe data is plotted below. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::plot(ex52$WindVelocity_xi_mph,\n           ex52$DCOutput_yi,\n           xlab = \"Wind Velocity, X\",\n           ylab = \"DC Output, Y\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nInspection of the scatter diagram indicates that the relationship between DC output $(y)$ and wind velocity $(x)$ may be nonlinear. However, we initially fit a straight-line model to the data, and look at the summary statistics. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm52 <- stats::lm(ex52$DCOutput_yi ~ ex52$WindVelocity_xi_mph, data = ex52)\nbase::summary(lm52)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nstats::lm(formula = ex52$DCOutput_yi ~ ex52$WindVelocity_xi_mph, \n    data = ex52)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.59869 -0.14099  0.06059  0.17262  0.32184 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               0.13088    0.12599   1.039     0.31    \nex52$WindVelocity_xi_mph  0.24115    0.01905  12.659 7.55e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2361 on 23 degrees of freedom\nMultiple R-squared:  0.8745,\tAdjusted R-squared:  0.869 \nF-statistic: 160.3 on 1 and 23 DF,  p-value: 7.546e-12\n```\n:::\n:::\n\n\nThe summary statistics for this model are $R^2=0.8745$, and $F_0=160.26$ (the P-value is <0.0001), and he regression model is: $\\hat y=0.1309+0.2411x$, shown in red below.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::plot(ex52$WindVelocity_xi_mph,\n           ex52$DCOutput_yi,\n           xlab = \"Wind Velocity, x\",\n           ylab = \"DC Output, Y\")\ngraphics::abline(lm52, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nBelow we can extract the fitted and residual values from our linear model, and then arrange them in order of increasing wind speed. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nex52$fitted <- stats::fitted(lm52)\nex52$resid <- stats::resid(lm52)\nex52 %>% dplyr::arrange(-dplyr::desc(ex52$WindVelocity_xi_mph)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    X ObservationNumber_i WindVelocity_xi_mph DCOutput_yi    fitted       resid\n1  25                  25                2.45       0.123 0.7216899 -0.59868986\n2   4                   4                2.70       0.500 0.7819771 -0.28197708\n3  11                  11                2.90       0.653 0.8302069 -0.17720685\n4   8                   8                3.05       0.558 0.8663792 -0.30837918\n5   3                   3                3.40       1.057 0.9507813  0.10621871\n6  16                  16                3.60       1.137 0.9990111  0.13798894\n7  24                  24                3.95       1.144 1.0834132  0.06058683\n8  23                  23                4.10       1.194 1.1195855  0.07441450\n9  13                  13                4.60       1.562 1.2401599  0.32184007\n10  1                   1                5.00       1.582 1.3366195  0.24538052\n11 20                  20                5.45       1.501 1.4451365  0.05586353\n12 14                  14                5.80       1.737 1.5295386  0.20746142\n13  2                   2                6.00       1.822 1.5777683  0.24423165\n14 10                  10                6.20       1.866 1.6259981  0.24000188\n15 12                  12                6.35       1.930 1.6621705  0.26782955\n16 19                  19                7.00       1.800 1.8189172 -0.01891722\n17 15                  15                7.40       2.088 1.9153768  0.17262323\n18 17                  17                7.85       2.179 2.0238938  0.15510624\n19  9                   9                8.15       2.166 2.0962384  0.06976158\n20 18                  18                8.80       2.112 2.2529852 -0.14098518\n21 21                  21                9.10       2.303 2.3253298 -0.02232985\n22  7                   7                9.55       2.294 2.4338468 -0.13984684\n23  6                   6                9.70       2.386 2.4700192 -0.08401917\n24  5                   5               10.00       2.236 2.5423638 -0.30636383\n25 22                  22               10.20       2.310 2.5905936 -0.28059360\n```\n:::\n:::\n\n\nThe residuals show a distinct pattern, that is, they move systematically from negative to positive and back to negative again as wind speed increases. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::plot(stats::fitted(lm52),\n           stats::resid(lm52),\n           ylab=TeX(r'($e_i$)'),\n           xlab=TeX(r'($\\hat{y}_i$)'),\n           pch = 16);graphics::abline(0, 0,lty = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThis residual plot indicates model inadequacy and implies that the linear relationship has not captured all of the information in the wind speed variable. Note that the curvature was apparent in the earlier scatter diagram, but is greatly amplified in the residual plot\n\nClearly some other model form must be considered. We might initially consider using a quadratic model such as: $y=\\beta_0+\\beta_1x+\\beta_2x^2+\\epsilon$ to account for the curvature. However since the quadratic model will eventually bend downward as wind speed increases, it would not be appropriate for these data. A more reasonable model for windmill data that incorporates an upper asymptote would be: $y=\\beta_0+\\beta_1(\\frac{1}{x})+\\epsilon$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nex52$xstar <- 1/ex52$WindVelocity_xi_mph\nlm52T <- stats::lm(ex52$DCOutput_yi ~ ex52$xstar, data = ex52)\nbase::summary(lm52T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nstats::lm(formula = ex52$DCOutput_yi ~ ex52$xstar, data = ex52)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.20547 -0.04940  0.01100  0.08352  0.12204 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2.9789     0.0449   66.34   <2e-16 ***\nex52$xstar   -6.9345     0.2064  -33.59   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.09417 on 23 degrees of freedom\nMultiple R-squared:   0.98,\tAdjusted R-squared:  0.9792 \nF-statistic:  1128 on 1 and 23 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe fitted regression model is $\\hat y=2.9789-6.9345x'$\n\nThe summary statistics for this model are $R^2=0.98$, and $F_0=1128$ (the p value is <0.0001).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::plot(stats::fitted(lm52T),\n           stats::rstudent(lm52T),\n           ylab=TeX(r'($t_i$)'),\n           xlab=TeX(r'($\\hat{y}_i$)'),\n           pch = 16);graphics::abline(0, 0,lty = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThis plot does not reveal any serious problems. \n\n# `4. Example 5.3: The Electic Utility Data`\n\nWe use the [Box-Cox](https://www.statisticshowto.com/probability-and-statistics/normal-distributions/box-cox-transformation/) procedure to select a variance-stabilizing transformation. The values of $SS_{Res}(\\lambda)$ for various values are shown in the table. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxcoxResult = MASS::boxcox(ex51$y_.kW. ~ ex51$x_.kWh., data = ex51, lambda = seq(-2,2,0.125))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThe Box-Cox graph shows most of the data is below the 95% confidence interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda <- boxcoxResult$x[which.max(boxcoxResult$y)]\nlambda\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5454545\n```\n:::\n:::\n\n\nWhere $\\lambda\\approx$ 0.5454545 could be used as an appropriate exponent to use to transform the data into a “normal shape.” \n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}